
<?php

	$request = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Request\Http');

	$moduleName = $request->getModuleName();
    $controller = $request->getControllerName();
    $action     = $request->getActionName();
    $route      = $request->getRouteName();

    $urlAction = $moduleName.'/'.$controller.'/'.$action.'/'.$route;

?>
<script>
require(['jquery'], function($) {


	$(document).bind("contextmenu",function(e){
  		return false;
    });

    
	$(document).ready(function(){
		$('.ox-megamenu-list').each(function(){
			var element = $(this).find('a .fa-chevron-down');
			element.addClass('fa-chevron-right');
			element.removeClass('fa-chevron-down');
		});
		
		$(window).scroll(function() {    
			var scroll = $(window).scrollTop();
		
			if (scroll >= 220) {
				$(".header__content-wrapper").addClass("fixedjioHeader");
			} else {
				$(".header__content-wrapper").removeClass("fixedjioHeader");
			}
		});
		
	});
	
});
</script>
<?php 
	if($urlAction == 'cms/page/view/cms')
	{
?>
	<script>
		require(['jquery'], function($) {
			$(document).ready(function(){

				$('.count').each(function () {
				    $(this).prop('Counter',0).animate({
				        Counter: $(this).text()
				    }, {
				        duration: 4000,
				        easing: 'swing',
				        step: function (now) {
				            $(this).text(Math.ceil(now));
				        }
				    });
				});
				
				
			});
			
		});
	</script>
<?php } ?>

<?php

    if( $urlAction == 'cms/index/index/cms'){
?>
<script>
    require(['jquery','owlcarousel'], function ($) {
    	$(document).ready(function(){
        //$(function(){
            $("#owl-demo").owlCarousel({
                items: 2,
                nav: true,
                dots: false,
                responsive:{
                    0:{
                        items: 1
                    },
                    768:{
                        items:2
                    }
                },
                navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"]
            });
        });

        $(".collapse").click(function(){
            var colapse_id = $(this).attr('colapse_id');
            
            if($('#collapse_'+colapse_id).is(':hidden'))
            {
                $('#collapse_'+colapse_id).show();
            }
            else
            {
                $('#collapse_'+colapse_id).hide();
            }
            
          });

    });
</script>	


<script>
    require(['jquery','owlcarousel'], function ($) {
        $(document).ready(function(){
            var sync1 = $(".slider");
				var sync2 = $(".navigation-thumbs");

				var thumbnailItemClass = '.owl-item';

				var slides = sync1.owlCarousel({
				    video:true,
				  startPosition: 12,
				  items:1,
				  loop:true,
				  margin:10,
				  autoplay:true,
				  autoplayTimeout:6000,
				  autoplayHoverPause:false,
				  nav: true,
				  dots: false
				}).on('changed.owl.carousel', syncPosition);

				function syncPosition(el) {
				  $owl_slider = $(this).data('owl.carousel');
				  var loop = $owl_slider.options.loop;

				  if(loop){
				    var count = el.item.count-1;
				    var current = Math.round(el.item.index - (el.item.count/2) - .5);
				    if(current < 0) {
				        current = count;
				    }
				    if(current > count) {
				        current = 0;
				    }
				  }else{
				    var current = el.item.index;
				  }

				  var owl_thumbnail = sync2.data('owl.carousel');
				  var itemClass = "." + owl_thumbnail.options.itemClass;


				  var thumbnailCurrentItem = sync2
				  .find(itemClass)
				  .removeClass("synced")
				  .eq(current);

				  thumbnailCurrentItem.addClass('synced');

				  if (!thumbnailCurrentItem.hasClass('active')) {
				    var duration = 300;
				    sync2.trigger('to.owl.carousel',[current, duration, true]);
				  }   
				}
				var thumbs = sync2.owlCarousel({
				  startPosition: 12,
				  items:4,
				  loop:false,
				  margin:10,
				  autoplay:false,
				  nav: false,
				  dots: false,
				  onInitialized: function (e) {
				    var thumbnailCurrentItem =  $(e.target).find(thumbnailItemClass).eq(this._current);
				    thumbnailCurrentItem.addClass('synced');
				  },
				})
				.on('click', thumbnailItemClass, function(e) {
				    e.preventDefault();
				    var duration = 300;
				    var itemIndex =  $(e.target).parents(thumbnailItemClass).index();
				    sync1.trigger('to.owl.carousel',[itemIndex, duration, true]);
				}).on("changed.owl.carousel", function (el) {
				  var number = el.item.index;
				  $owl_slider = sync1.data('owl.carousel');
				  $owl_slider.to(number, 100, true);
				});

            
            
        });

    });
</script>

<?php } ?>