/**
* Athlete2
* Theme by Olegnax
* Copyright (c) 2020 Olegnax 
* https://olegnax.com/
*
* WARNING: Do not change this file. Your changes will be lost.
* <?php echo date( "Y-m-d H:i:s" ); ?>
*/
/*
<?php
$at_settings		 = $this->getConfig( 'athlete2_settings', $this->getData( 'dynamic_store_code' ) );
$at_appearance		 = $this->getConfig( 'athlete2_design', $this->getData( 'dynamic_store_code' ) );
$_helper = $this->helper( 'Olegnax\Athlete2\Helper\CssFiles' );
$_helper->setStoreCode( $this->getData( 'dynamic_store_code' ) );
?>
*/
<?php if($at_settings['footer']['footer_store_switcher_font_style']): ?>
.page-footer .switcher .options .action.toggle strong{
	font-family: '<?php if($_helper->getFont( 'general_font' )) { echo $_helper->getFont( 'general_font' ); } else { 'Open Sans'; } ?>', 'Helvetica Neue', Helvetica, Arial, sans-serif;
	font-weight: <?php if(!empty($at_appearance[ 'appearance_general' ][ 'text_font_weight_small' ])) { echo $at_appearance[ 'appearance_general' ][ 'text_font_weight_small' ]; } else { echo '700'; } ?>;
	font-size: 1.4rem;
    text-transform:uppercase;
    letter-spacing: <?php if(!empty($at_appearance[ 'appearance_general' ][ 'text_letter_spacing_small' ])) { echo $at_appearance[ 'appearance_general' ][ 'text_letter_spacing_small' ] . 'px'; } else { echo '-0.03em'; } ?>;;
}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'website_bg_color' ])): ?>
body { background-color: <?php echo $at_appearance[ 'appearance_general' ][ 'website_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_settings[ 'general' ][ 'content_maxwidth' ])): ?>
@media (min-width: 768px){
	.container,
	.navigation, .ox-megamenu, .breadcrumbs, .page-header .header.panel, .header.content, .footer.content, .page-wrapper>.widget, .page-wrapper>.page-bottom, .block.category.event, .top-container, .page-main {
		max-width: <?php echo $at_settings['general']['content_maxwidth']; ?>px;
	}
}
<?php endif; ?>
<?php if(!empty($at_settings[ 'products_listing' ][ 'grid_fullwidth' ])): ?>
.catalogsearch-result-index .page-main,
.catalog-category-view .page-main{ max-width: 100%!important; }
<?php endif; ?>
<?php if(!empty($at_settings[ 'product' ][ 'product_fullwidth' ])): ?>
.catalog-product-view .page-main{ max-width: 100%!important; }
<?php endif; ?>
<?php 
$product_gallery_width = '';
$product_content_width = '';
if(!empty($at_settings[ 'product' ][ 'product_gallery_fixed_size' ])){
	if(!empty($at_settings[ 'product_images' ][ 'product_image_width' ])){
		$product_gallery_width = (int) $at_settings[ 'product_images' ][ 'product_image_width' ];
		$product_content_width = 'calc(95% - ' . $product_gallery_width . 'px)';
		$product_gallery_width .= 'px';
	}
} else {
	if(!empty($at_settings[ 'product' ][ 'product_gallery_width' ])){
		$product_gallery_width = (int) $at_settings[ 'product' ][ 'product_gallery_width' ];
		$product_content_width = 95 - $product_gallery_width . '%';
		$product_gallery_width .= '%';
	}
}
if(!empty($product_gallery_width)): ?>
@media (min-width: 1025px), print{
	.page-layout-1column-fullwidth .product.media, 
	.page-layout-1column .product.media {
		width: <?php echo $product_gallery_width; ?>;
	}
	.page-layout-1column-fullwidth .product-info-main, 
	.page-layout-1column .product-info-main {
		width: <?php echo $product_content_width; ?>;
	}
}
<?php endif; ?>

/* Logo Settigns */
<?php 
$logoWidth = $at_settings[ 'logo' ][ 'logo_width' ];
$logoPaddingHorizontal = $at_settings[ 'logo' ][ 'logo_padding_horizontal' ]; 
?>
<?php if($logoPaddingHorizontal != '' ): ?>
.logo__container { padding-left: <?php echo $logoPaddingHorizontal; ?>px; padding-right: <?php echo $logoPaddingHorizontal; ?>px; }
<?php endif; ?>
	<?php if($at_settings[ 'logo' ][ 'logo_padding_vertical' ] != ''): ?>
.logo__container { padding-top: <?php echo $at_settings[ 'logo' ][ 'logo_padding_vertical' ]; ?>px; padding-bottom: <?php echo $at_settings[ 'logo' ][ 'logo_padding_vertical' ]; ?>px; }
<?php endif; ?>

<?php if($at_settings[ 'logo' ][ 'mobile_logo_padding_horizontal' ] != '' ): ?>
@media only screen and (max-width: 1024px){
.logo__container { padding-left: <?php echo $at_settings[ 'logo' ][ 'mobile_logo_padding_horizontal' ]; ?>px; padding-right: <?php echo $at_settings[ 'logo' ][ 'mobile_logo_padding_horizontal' ]; ?>px; }
}
<?php endif; ?>
<?php if($at_settings[ 'logo' ][ 'mobile_logo_padding_vertical' ] != '' ): ?>
@media only screen and (max-width: 1024px){
.logo__container { padding-top: <?php echo $at_settings[ 'logo' ][ 'mobile_logo_padding_vertical' ]; ?>px; padding-bottom: <?php echo $at_settings[ 'logo' ][ 'mobile_logo_padding_vertical' ]; ?>px; }
}
<?php endif; ?>
<?php if(!empty($logoWidth)): ?>
@media only screen and (max-width: 1024px){
.mobile-header--layout-4 .logo__container{ max-width: <?php echo $logoWidth; ?>px; }
}
@media (min-width: 1025px){
	.header--layout-1 .logo__container,
	.logo__container {
		width: <?php echo $logoWidth; ?>px;
	}
}
@media (min-width: 641px){
.mobile-header--layout-1 .logo__container{
	width: <?php echo $logoWidth; ?>px;
}
}
<?php endif; ?>

/* Retina logo */
<?php if ( isset( $at_settings['logo']['logo_upload_retina'] ) && ! empty( $at_settings['logo']['logo_upload_retina'] ) ) { ?>
    @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi){
        .logo__container .logo img{
            display:none;
        }
		.logo__container .logo img.retina{
			display:block;
		}
    }
<?php } ?>
/* logo size calc */
<?php 
$logoMobilePaddingHorizontal = $at_settings[ 'logo' ][ 'mobile_logo_padding_horizontal' ]; 
if($logoMobilePaddingHorizontal == ''){
	$logoMobilePaddingHorizontal = 20; 
}
if($logoPaddingHorizontal == ''){
	$logoPaddingHorizontal = 20; 
}
if($logoWidth=='' || empty($logoWidth)){
	$logoWidth = 210; 
}
?>
@media (min-width: 1025px){	
	.logo__container .logo img{ max-width: <?php echo ($logoWidth - $logoPaddingHorizontal*2) ?>px; }
}
@media (max-width: 1024px){	
	.logo__container .logo img{ max-width: <?php echo ($logoWidth - $logoMobilePaddingHorizontal*2) ?>px; }
}

/* Links */

/* Basic links */
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'links_hover' ])): ?>
.block-reorder .actions-toolbar .action.view:hover,
a:hover, .alink:hover { color:<?php echo $at_appearance[ 'appearance_general' ][ 'links_hover' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'input_label_color' ])): ?>
.swatch-attribute-label,
.field > .label { color:<?php echo $at_appearance[ 'appearance_general' ][ 'input_label_color' ]; ?> }
<?php endif; ?>

/* Links with bg */
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'links_color' ])): ?>
a, .alink,
a:visited, .alink:visited,
.filter-options-content a,
.breadcrumbs a, .reviews-actions a,
.post-view .post-meta a.item,
.block-reorder .actions-toolbar .action.view,
a.bg-hover, .std a, .links-bg-hover a{ color:<?php echo $at_appearance[ 'appearance_general' ][ 'links_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'bg_links_hover' ])): ?>
.ox-megamenu__dropdown .ox-owl-nav button.owl-next:hover span:after, 
.ox-megamenu__dropdown .ox-owl-nav button.owl-prev:hover span:after, 
.ox-megamenu__dropdown .ox-owl-nav button.owl-next:hover span:before, 
.ox-megamenu__dropdown .ox-owl-nav button.owl-prev:hover span:before,
.ox-brand-slider__container .ox-owl-nav button.owl-prev:hover span:after,
.ox-brand-slider__container .ox-owl-nav button.owl-next:hover span:after,
.ox-brand-slider__container .ox-owl-nav button.owl-prev:hover span:before,
.ox-brand-slider__container .ox-owl-nav button.owl-next:hover span:before { background-color: <?php echo $at_appearance[ 'appearance_general' ][ 'bg_links_hover' ]; ?>  }

.sidebar-additional .block.block-recent-posts .item a:hover,
.sidebar-additional .block.block-archive .item a:hover,
.sidebar-additional .block.block-categories li a:hover,
.post-view .block.comments .c-comment .p-actions a:hover,
.post-view .post-nextprev-hld .nextprev-link:hover .h3,
.post-view .post-meta a.item:hover,
.abs-discount-block > .title:hover:after, .cart-summary .block > .title:hover:after, .opc-block-summary .items-in-cart > .title:hover:after, 
.checkout-payment-method .payment-option._collapsible > .title:hover:after, .paypal-review-discount .block > .title:hover:after,
.filter-options-content a:hover,
.filter.block .content dl.options dd li a:hover,
.breadcrumbs a:hover, .reviews-actions a:hover,
a.bg-hover:hover, .std a:hover, .links-bg-hover a:hover { color:<?php echo $at_appearance[ 'appearance_general' ][ 'bg_links_hover' ]; ?> }

<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'bg_links_hover_bg' ])): ?>
.sidebar-additional .block.block-recent-posts .item a:hover,
.sidebar-additional .block.block-archive .item a:hover,
.sidebar-additional .block.block-categories li a:hover,
.post-view .block.comments .c-comment .p-actions a:hover,
.post-view .post-nextprev-hld .nextprev-link:hover .h3,
.post-view .post-meta a.item:hover,
.ox-megamenu__dropdown .ox-owl-nav button.owl-next:hover, 
.ox-megamenu__dropdown .ox-owl-nav button.owl-prev:hover,
.ox-brand-slider__container .ox-owl-nav button.owl-next:hover, 
.ox-brand-slider__container .ox-owl-nav button.owl-prev:hover,
.cart-summary .block > .title:hover:after, .opc-block-summary .items-in-cart > .title:hover:after, 
.checkout-payment-method .payment-option._collapsible > .title:hover:after, .paypal-review-discount .block > .title:hover:after,
.filter-options-content a:hover,
.filter.block .content dl.options dd li a:hover,
.breadcrumbs a:hover, .reviews-actions a:hover,
a.bg-hover:hover, .std a:hover, .links-bg-hover a:hover { background-color:<?php echo $at_appearance[ 'appearance_general' ][ 'bg_links_hover_bg' ]; ?> }
<?php endif; ?>


<?php if(!empty($at_appearance[ 'appearance_general' ][ 'main_color' ])): ?>
.products-grid .product-item:hover .price-box .price-container .price,
.extended-review-summary .ratings-value,
.ox-prev-next__link .label,
.header--layout-4.page-header .ox-megamenu > ul > .level0.active > .level-top,
.header--layout-4.page-header .navigation > ul > .level0.active > .level-top,
.header--layout-4.page-header .ox-megamenu > ul > .level0:hover > .level-top,
.header--layout-4.page-header .navigation > ul > .level0:hover > .level-top,
.rating-summary .rating-result > span:before,
.review-list .rating-summary .rating-result > span:before,
.review-control-vote label:before,
.accent-color,
.post-view .social-share__content a:hover i,
.ox-prev-next__link .label{ color:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }

button:focus,
button:active,
button:hover,
.ox-toggle.medium-left .ox-toggle-title:hover .toggle-minus,
.abs-action-link-button:focus,
.abs-action-link-button:active,
.abs-action-addto-product:focus,
.abs-action-addto-product:active,
.block-event .slider-panel .slider .item .action.event:focus,
.block-event .slider-panel .slider .item .action.event:active,
.bundle-options-container .block-bundle-summary .product-addto-links > .action:focus,
.bundle-options-container .block-bundle-summary .product-addto-links > .action:active,
.abs-action-link-button:hover,
.abs-action-addto-product:hover,
.block-event .slider-panel .slider .item .action.event:hover,
.bundle-options-container .block-bundle-summary .product-addto-links > .action:hover,
.sidebar .action.delete:hover:before,
.block-compare .action.delete:hover:before,
.abs-shopping-cart-items .action.continue:after,
.block-cart-failed .action.continue:after,
.cart-container .form-cart .action.continue:after,
.abs-shopping-cart-items .action.clear:after,
.block-cart-failed .action.clear:after,
.cart-container .form-cart .action.clear:after,
.abs-shopping-cart-items .action.update:after,
.block-cart-failed .action.update:after,
.cart-container .form-cart .action.update:after,
.message.warning:before,
.hightlighted-text:before,
.slide-out-menu--mobile .hamburger-menu-icon-small span,
.top-bar .switcher:hover,
.page-footer .switcher:hover .options .action.toggle,
.page-footer .switcher .options .action.toggle.active 
.page-header .header.links a:not(.button):hover,
.footer.content a.athlete2-social-icon,
.footer.content a:not(.button).athlete2-social-icon,
.content a.athlete2-social-icon,
.std a.athlete2-social-icon,
.athlete2-social-icons > a.athlete2-social-icon,
a.athlete2-social-icon,
.primary > .action,
a.action.primary,
.action.primary,
.button.primary,
a.button.primary,
a.button,
.button,
button,
.primary > .action.naked:after,
a.action.primary.naked:after,
.action.primary.naked:after,
.button.primary.naked:after,
a.button.primary.naked:after,
a.button.naked:after,
.button.naked:after,
button.naked:after,
.button.secondary:after,
a.button.secondary:after,
.action.secondary:after,
.action-secondary:after,
button.action-secondary:after,
button.action.secondary:after,
.secondary > a.action:after,
.pages strong.page,
.ui-dialog.popup .action.close:hover,
.action-search-slideout,
.page-header .navigation .level0 > .level-top:before,
.logo__container,
#ox_quickview_wrapper .ox-overlay-close-btn:hover,
.fotorama__active .fotorama__dot,
.owl-carousel .owl-dots button.owl-dot.active span,
.owl-carousel .owl-dots button.owl-dot:hover span,
.crosssell .owl-carousel .owl-nav button.owl-next:after,
.related .owl-carousel .owl-nav button.owl-next:after,
.upsell .owl-carousel .owl-nav button.owl-next:after,
.crosssell .owl-carousel .owl-nav button.owl-prev:after,
.related .owl-carousel .owl-nav button.owl-prev:after,
.upsell .owl-carousel .owl-nav button.owl-prev:after,
.owl-carousel.widget-product-grid .owl-nav button.owl-next:after,
.owl-carousel.widget-product-grid .owl-nav button.owl-prev:after,
.owl-nav button.owl-next:after,
.owl-nav button.owl-prev:after,
#toTop,
.header-top-banner,
.at-close-cross:hover,
.ox-banner-animated-text .ox-banner-animated-container .text.accent-bg:after,
.ox-banner-animated-text .ox-banner-animated-container .text:after,
.ox-banner-animated-text .ox-banner-animated-container .link,
.modal-custom .action-close:focus,
.modal-popup .action-close:focus,
.modal-slide .action-close:focus,
.modal-custom .action-close:hover,
.modal-popup .action-close:hover,
.modal-slide .action-close:hover,
.ox-banner__text-container .text:after,
.ox-banner__text-container .link,
.athlete-slideshow .slide .controls .slide-control:after,
.athlete-slideshow .slide .controls .progress,
.slide-title .link,
.cart-summary .actions-toolbar > .primary button,
.cart-summary .actions-toolbar > .primary button.naked:after,
.minicart-wrapper .action.showcart,
.opc-progress-bar-item._active:before,
.opc-block-shipping-information .shipping-information-title .action-edit:after,
.action.action-edit-address:after,
.gift-item-block .title:focus,
.gift-item-block .title:active,
.sorter-action:hover,
.js-toolbar-switch:hover,
.js-toolbar-dropdown > div:hover,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover,
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover,
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover,
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover,
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover,
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover,
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover,
.table-comparison .cell.remove .action.delete:hover,
.table-comparison .action.towishlist:hover,
.table-comparison .action.tocart:hover,
.filter-current .action.remove:hover:before,
.extended-review-summary-wrapper .number-of-ratings .rating-result span:before,
.extended-review-summary .ratings-count .rating-result span:before,
.footer.content a:hover,
.sidebar-additional .block:before,
.block-event .slider-panel .slider .item .action.event,
.ox-product-scroll__amount .amount-count-line span,
.toolbar-amount .amount-count-line span, 
.opc-progress-bar-item._active:before,
.slider-progress:after,
.animated-text--bg.accent:after,
.post-view .post-categories a,
.post-list.blog-style-modern article .post-categories a,
.post-list.blog-style-classic .post-date .hover,
.post-view .post-tags a:hover,
blockquote:after,
blockquote:before,
.sidebar-additional .block.block-tagclaud a:hover,
.filter-options-content .mana-filter-slider > .mana-slider-span,
.filter-options-content .ui-slider .ui-slider-range,
.filter-options-content .ox-price-slider .ui-slider-range,
.filter-options-content .noUi-connect,
.filter-current-count,
#toTop { background:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }

@media only screen and (max-width: 1024px) {
.order-links .item.current strong,
.ox-nav-sections-item-title.active:after, 
.product.data.items > .item.title:not(.disabled) > .switch:focus,
.product.data.items > .item.title:not(.disabled) > .switch:hover,
.product.data.items > .item.title:not(.disabled) > .switch:active,
.product.data.items > .item.title.active > .switch,
.product.data.items > .item.title.active > .switch:focus,
.product.data.items > .item.title.active > .switch:hover { background:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }
}

@media all and (min-width: 1025px), print {
	.order-links .item.current strong,
	.product.data.items > .item.title > .switch:after,
	.header--layout-4 .minicart-wrapper .action.showcart:after,
	.ox-megamenu-navigation .category-item.has-active > .level-top,
	.ox-megamenu-navigation .category-item.active > .level-top,
	.ox-megamenu-navigation .category-item.has-active > a,
	.ox-megamenu-navigation .category-item.active > a,
	.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item.active > a,
	.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item.active > a,
	.modes-mode.active,
	.modes-mode:hover,
	.block-search .action.search,
	.ox-megamenu-navigation > .level0 > a:before { background:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }
}

@media all and (min-width: 1025px), print {
  .ox-megamenu-navigation .ox-megamenu__dropdown .category-item.active > a,
  .ox-megamenu-navigation .ox-megamenu__dropdown .category-item.active + .category-item > a { border-color:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }
}
.post-view .block.comments .c-comment .c-post,
.post-list.blog-style-modern article .post-links > .item:hover,
.filter-options,
.filter.block .content,
.a-underlined-links a,
.underlined-links a:hover,
.account-nav .content { border-color:<?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?> }

.accent-color svg,
svg.accent-color { fill: <?php echo $at_appearance[ 'appearance_general' ][ 'main_color' ]; ?>!important }
<?php endif; ?>

/* Typography */

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'body_color' ])): ?>
.ox-megamenu,
body{ color:<?php echo $at_appearance[ 'appearance_general' ][ 'body_color' ]; ?> }
@media only screen and (max-width: 639px){
.table-wrapper .table:not(.cart):not(.totals):not(.table-comparison) > tbody > tr td[data-th]:before,
.table-wrapper .table:not(.cart):not(.totals):not(.table-comparison) > tbody > tr th[data-th]:before { color:<?php echo $at_appearance[ 'appearance_general' ][ 'body_color' ]; ?> }
}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'highlight_color' ])): ?>
.hightlighted-text:before { background-color: <?php echo $at_appearance[ 'appearance_general' ][ 'highlight_color' ]; ?>}
<?php endif; ?>

/* Headings */

<?php if(!empty($at_appearance[ 'appearance_general' ][ 'titles_color' ])): ?>
.multicheckout .box-title > span, 
.paypal-review .block .box-title > span, 
.magento-rma-guest-returns .column.main .block:not(.widget) .box-title > span, 
[class^='sales-guest-'] .column.main .block:not(.widget) .box-title > span, 
.sales-guest-view .column.main .block:not(.widget) .box-title > span, 
.account .column.main .block:not(.widget) .box-title > span,
.abs-account-blocks .block-title > strong, 
.block-giftregistry-results .block-title > strong, 
.block-giftregistry-shared-items .block-title > strong, 
.block-wishlist-search-results .block-title > strong, 
.widget .block-title > strong, 
.multicheckout .block-title > strong, 
.paypal-review .block .block-title > strong, 
.magento-rma-guest-returns .column.main .block:not(.widget) 
[class^='sales-guest-'] .column.main .block:not(.widget) .block-title > strong, 
.sales-guest-view .column.main .block:not(.widget) .block-title > strong, 
.account .column.main .block:not(.widget) .block-title > strong,
.cart-empty-big-text,
.fieldset > .legend,
.cart-summary > .title,
.fieldset .review-legend.legend,
.review-list .block-title strong,
.filter.block .content dl.options dt,
.sidebar-additional .block .block-title > strong,
.bundle-options-container .block-bundle-summary > .title > strong,
.bundle-options-container .block-bundle-summary .bundle-summary > .subtitle,
.bundle-options-container .legend.title,
.opc-wrapper .step-title, .opc-block-shipping-information .shipping-information-title, .opc-block-summary > .title, .checkout-agreements-items .checkout-agreements-item-title,
.review-title,
.post-list.blog-style-classic article .post-title a,
.post-list.blog-style-modern article .post-title a,
.post-list.blog-style-modern article .post-title,
.post-view .block.comments .c-count,
.post-view .block.comments .c-comment .p-name,
.modal-popup .modal-title,
.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {	color:<?php echo $at_appearance[ 'appearance_general' ][ 'titles_color' ]; ?>;}
<?php endif; ?>

<?php if($_helper->getFont( 'body_font' )): ?>
.ox-megamenu,
body {	font-family: '<?php echo $_helper->getFont( 'body_font' ); ?>', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if($_helper->getFont( 'title_font' )): ?>
.abs-account-blocks .block-title > strong, 
.block-giftregistry-results .block-title > strong, 
.block-giftregistry-shared-items .block-title > strong, 
.block-wishlist-search-results .block-title > strong, 
.widget .block-title > strong, 
.multicheckout .block-title > strong, 
.paypal-review .block .block-title > strong, 
.magento-rma-guest-returns .column.main .block:not(.widget) 
[class^='sales-guest-'] .column.main .block:not(.widget) .block-title > strong, 
.sales-guest-view .column.main .block:not(.widget) .block-title > strong, 
.account .column.main .block:not(.widget) .block-title > strong,
.cart-empty-big-text,
.block.newsletter.newsletter-style--big .title,
.ox-overlay .header__search-wrapper form input,
.ox-overlay .header__search-wrapper form .label,
.ox-slideout .header__search-wrapper form input,
.ox-slideout .header__search-wrapper form .label,
.cart-summary > .title,
.fieldset .review-legend.legend,
.review-list .block-title strong,
.bundle-options-container .block-bundle-summary > .title > strong,
.bundle-options-container .block-bundle-summary .bundle-summary > .subtitle,
.column.main .block .title strong, .block .title strong, .block-title strong,
.bundle-options-container .legend.title,
.opc-wrapper .step-title, .opc-block-shipping-information .shipping-information-title, .opc-block-summary > .title, .checkout-agreements-items .checkout-agreements-item-title,
.extended-review-summary .ratings-value,
.post-view .block.comments .c-count,
.modal-popup .modal-title,
.h1, .h2, .h3, h1, h2, h3 {	font-family: '<?php echo $_helper->getFont( 'title_font' ); ?>', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if($_helper->getFont( 'general_font' )): ?>
.multicheckout .box-title > span, 
.paypal-review .block .box-title > span, 
.magento-rma-guest-returns .column.main .block:not(.widget) .box-title > span, 
[class^='sales-guest-'] .column.main .block:not(.widget) .box-title > span, 
.sales-guest-view .column.main .block:not(.widget) .box-title > span, 
.account .column.main .block:not(.widget) .box-title > span,
.block.newsletter .title,
.minicart-wrapper .action.showcart,
.ox-banner .text,
.ox-banner-animated-text .ox-banner-animated-container .text,
.ox-banner__text-container .text,
.filter-options-title,
.filter .block-subtitle,
.small-subtitle,
.fieldset > .legend,
.opc-progress-bar-item > span,
.filter.block .content dl.options dt,
.sidebar-additional .block .block-title > strong,
.review-title,
.post-list.blog-style-modern article .post-title,
.post-list.blog-style-modern article .post-image-wrapper .post-posed-date,
.post-list.blog-style-modern article .post-categories a,
.post-list.blog-style-modern article .post-links > .item,
.post-list.blog-style-classic .post-date .day,
.post-list.blog-style-classic .post-date .hover,
.post-view .post-categories a,
.post-view .block.comments .c-comment .p-name,
.h4, .h5, .h6, h4, h5, h6 {	font-family: '<?php echo $_helper->getFont( 'general_font' ); ?>', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>

/* Letter Spacing */
<?php if($at_appearance[ 'appearance_general' ][ 'text_letter_spacing_big' ] != ''): ?>
.ox-overlay .header__search-wrapper form input,
.ox-overlay .header__search-wrapper form .label,
.ox-slideout .header__search-wrapper form input,
.ox-slideout .header__search-wrapper form .label,
.h1, h1, h1.big, .h1.big {	letter-spacing: <?php echo $at_appearance[ 'appearance_general' ][ 'text_letter_spacing_big' ]; ?>px;}
<?php endif; ?>
<?php if($at_appearance[ 'appearance_general' ][ 'text_letter_spacing_medium' ] != '' ): ?>
.abs-account-blocks .block-title > strong, 
.block-giftregistry-results .block-title > strong, 
.block-giftregistry-shared-items .block-title > strong, 
.block-wishlist-search-results .block-title > strong, 
.widget .block-title > strong, 
.multicheckout .block-title > strong, 
.paypal-review .block .block-title > strong, 
.magento-rma-guest-returns .column.main .block:not(.widget) 
[class^='sales-guest-'] .column.main .block:not(.widget) .block-title > strong, 
.sales-guest-view .column.main .block:not(.widget) .block-title > strong, 
.account .column.main .block:not(.widget) .block-title > strong,
.cart-empty-big-text,
.ox-banner-animated-text.ox-banner-medium .ox-banner__text-container .text,
.ox-banner-animated-text.ox-banner-big .ox-banner__text-container .text,
.block.newsletter.newsletter-style--big .title,
.ox-banner__text-container .text,
.column.main .block .title strong, .block .title strong, .block-title strong,
.cart-summary > .title,
.fieldset .review-legend.legend,
.review-list .block-title strong,
.bundle-options-container .block-bundle-summary > .title > strong,
.bundle-options-container .block-bundle-summary .bundle-summary > .subtitle,
.bundle-options-container .legend.title,
.post-view .block.comments .c-count,
.modal-popup .modal-title,
.opc-wrapper .step-title, .opc-block-shipping-information .shipping-information-title, .opc-block-summary > .title, .checkout-agreements-items .checkout-agreements-item-title,
.h2, .h3, h2, h3 {	letter-spacing: <?php echo $at_appearance[ 'appearance_general' ][ 'text_letter_spacing_medium' ]; ?>px;}
<?php endif; ?>
<?php if($at_appearance[ 'appearance_general' ][ 'text_letter_spacing_small' ] != '' ): ?>
.multicheckout .box-title > span, 
.paypal-review .block .box-title > span, 
.magento-rma-guest-returns .column.main .block:not(.widget) .box-title > span, 
[class^='sales-guest-'] .column.main .block:not(.widget) .box-title > span, 
.sales-guest-view .column.main .block:not(.widget) .box-title > span, 
.account .column.main .block:not(.widget) .box-title > span,
.block.newsletter .title,
.ox-banner .text,
.ox-banner-animated-text .ox-banner-animated-container .text,
.filter-options-title,
.filter .block-subtitle,
.login-container .block-new-customer .block-title strong,
.ox-overlay .header__search-wrapper form .input-focused .label,
.fieldset > .legend,
.opc-progress-bar-item > span,
.filter.block .content dl.options dt,
.sidebar-additional .block .block-title > strong,
.review-title,
.post-list.blog-style-modern article .post-image-wrapper .post-posed-date,
.post-list.blog-style-modern article .post-categories a,
.post-list.blog-style-modern article .post-links > .item,
.post-list.blog-style-classic .post-date .day,
.post-list.blog-style-classic .post-date .hover,
.post-list.blog-style-modern article .post-title,
.post-view .post-categories a,
.post-view .block.comments .c-comment .p-name,
.column.main .cart-summary .block > .title strong, .column.main .opc-block-summary .items-in-cart > .title strong, .column.main .checkout-payment-method .payment-option._collapsible > .title strong, .column.main .paypal-review-discount .block > .title strong,
.h4, .h5, .h6, h4, h5, h6 {	letter-spacing: <?php echo $at_appearance[ 'appearance_general' ][ 'text_letter_spacing_small' ]; ?>px;}
<?php endif; ?>

/* Font Weight */
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'text_font_weight_big' ])): ?>
.ox-overlay .header__search-wrapper form input,
.ox-overlay .header__search-wrapper form .label,
.ox-slideout .header__search-wrapper form input,
.ox-slideout .header__search-wrapper form .label,
.h1, h1, h1.big, .h1.big {	font-weight: <?php echo $at_appearance[ 'appearance_general' ][ 'text_font_weight_big' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'text_font_weight_medium' ])): ?>
.abs-account-blocks .block-title > strong, 
.block-giftregistry-results .block-title > strong, 
.block-giftregistry-shared-items .block-title > strong, 
.block-wishlist-search-results .block-title > strong, 
.widget .block-title > strong, 
.multicheckout .block-title > strong, 
.paypal-review .block .block-title > strong, 
.magento-rma-guest-returns .column.main .block:not(.widget) 
[class^='sales-guest-'] .column.main .block:not(.widget) .block-title > strong, 
.sales-guest-view .column.main .block:not(.widget) .block-title > strong, 
.account .column.main .block:not(.widget) .block-title > strong,
.cart-empty-big-text,
.ox-banner-animated-text.ox-banner-medium .ox-banner__text-container .text,
.ox-banner-animated-text.ox-banner-big .ox-banner__text-container .text,
.block.newsletter.newsletter-style--big .title,
.ox-banner__text-container .text,
.column.main .block .title strong, .block .title strong, .block-title strong,
.opc-wrapper .step-title, .opc-block-shipping-information .shipping-information-title, .opc-block-summary > .title, .checkout-agreements-items .checkout-agreements-item-title,
.fieldset .review-legend.legend,
.review-list .block-title strong,
.bundle-options-container .block-bundle-summary > .title > strong,
.bundle-options-container .block-bundle-summary .bundle-summary > .subtitle,
.bundle-options-container .legend.title,
.post-view .block.comments .c-count,
.modal-popup .modal-title,
.h2, .h3, h2, h3 {	font-weight: <?php echo $at_appearance[ 'appearance_general' ][ 'text_font_weight_medium' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_general' ][ 'text_font_weight_small' ])): ?>
.multicheckout .box-title > span, 
.paypal-review .block .box-title > span, 
.magento-rma-guest-returns .column.main .block:not(.widget) .box-title > span, 
[class^='sales-guest-'] .column.main .block:not(.widget) .box-title > span, 
.sales-guest-view .column.main .block:not(.widget) .box-title > span, 
.account .column.main .block:not(.widget) .box-title > span,
.block.newsletter .title,
.ox-banner .text,
.ox-banner-animated-text .ox-banner-animated-container .text,
.filter-options-title,
.filter .block-subtitle,
.login-container .block-new-customer .block-title strong,
.filter-options-title strong,
.fieldset > .legend,
.filter.block .content dl.options dt,
.sidebar-additional .block .block-title > strong,
.review-title,
.post-list.blog-style-modern article .post-image-wrapper .post-posed-date,
.post-list.blog-style-modern article .post-categories a,
.post-list.blog-style-modern article .post-links > .item,
.post-list.blog-style-classic .post-date .day,
.post-list.blog-style-classic .post-date .hover,
.post-list.blog-style-modern article .post-title,
.post-view .post-categories a,
.post-view .block.comments .c-comment .p-name,
.column.main .cart-summary .block > .title strong, .column.main .opc-block-summary .items-in-cart > .title strong, .column.main .checkout-payment-method .payment-option._collapsible > .title strong, .column.main .paypal-review-discount .block > .title strong,
.h4, .h5, .h6, h4, h5, h6 {	font-weight: <?php echo $at_appearance[ 'appearance_general' ][ 'text_font_weight_small' ]; ?>;}
<?php endif; ?>



/* Header Appearance */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'header_bg' ])): ?>
.page-header, .page-header .sticky-wrapper { background: <?php echo $at_appearance[ 'appearance_header' ][ 'header_bg' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_header' ][ 'logo_bg' ])): ?>
.header--layout-4 .header__content .logo__container:before,
.logo__container { background: <?php echo $at_appearance[ 'appearance_header' ][ 'logo_bg' ]; ?>; }
<?php endif; ?>

/* Top Bar */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_bg' ])): ?>
.top-bar, .top-bar:before { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_bg' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_color' ])): ?>
.top-bar, 
.top-bar .switcher, 
.top-bar .topline-block a:not(.button),
.top-bar .header.links a:not(.button) { color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_links_color_hover' ])): ?>
.top-bar .switcher:hover, 
.top-bar .topline-block a:not(.button):hover,
.top-bar .header.links a:not(.button):hover { color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_links_color_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_links_bg' ])): ?>
.top-bar .switcher:hover, 
.top-bar .topline-block a:not(.button):hover,
.top-bar .header.links a:not(.button):hover { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_links_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_text_font_size' ])): ?>
.top-bar, 
.top-bar .topline-block,
.top-bar .topline-block a:not(.button),
.top-bar .header.links a:not(.button){ font-size: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_text_font_size' ]; ?>px; }
<?php endif; ?>

/* Minicart Action */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_icon_bg' ])): ?>
.minicart-wrapper .action.showcart { background: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_icon_color' ])): ?>
.minicart-wrapper .action.showcart, .minicart-wrapper .action.showcart span { color: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_color' ]; ?>; }
.minicart-wrapper .action.showcart svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_icon_bg_hover' ])): ?>
.header--layout-4 .minicart-wrapper .action.showcart:after,
.header--layout-2 .minicart-wrapper .action.showcart:hover,
.header--layout-1 .minicart-wrapper .action.showcart:hover { background: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_icon_color_hover' ])): ?>
.minicart-wrapper .action.showcart:hover, .minicart-wrapper .action.showcart:hover span { color: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_color_hover' ]; ?>; }
.minicart-wrapper .action.showcart:hover svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_icon_color_hover' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_counter_bg' ])): ?>
.minicart-btn--minimal .minicart-wrapper .action.showcart span.qty { background: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_counter_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'minicart_counter_text' ])): ?>
.minicart-btn--minimal .minicart-wrapper .action.showcart span.qty .counter-number,
.minicart-btn--minimal .minicart-wrapper .action.showcart span.qty { color: <?php echo $at_appearance[ 'appearance_header' ][ 'minicart_counter_text' ]; ?>; }
<?php endif; ?>

/* Header Items */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'header_item_icon_bg' ])): ?>
.header__content .header__item .button { background: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'header_item_icon_color' ])): ?>
.header__content .header__item .button svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_color' ]; ?>; }
.header__content .header__item .button i { color: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'header_item_icon_bg_hover' ])): ?>
.header__content .header__item .button:hover { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'header_item_icon_color_hover' ])): ?>
.header__content .header__item .button:hover svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_color_hover' ]; ?>; }
.header__content .header__item .button:hover i { color: <?php echo $at_appearance[ 'appearance_header' ][ 'header_item_icon_color_hover' ]; ?>; }
<?php endif; ?>

/* Header Search Action */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_icon_bg' ])): ?>
.header__content .block-search .action.search, .header__content .block-search .action-search-slideout { background: <?php echo $at_appearance[ 'appearance_header' ][ 'search_icon_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_icon_color' ])): ?>
.header__content .block-search .action.search svg, .header__content a.button.action-search-slideout svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'search_icon_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_icon_bg_hover' ])): ?>
/*.header__content .block-search .action.search:after, 
.header__content .block-search .action-search-slideout:after,*/
.header__content .block-search .action.search:after, 
.header__content .block-search .action-search-slideout:hover { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'search_icon_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_icon_color_hover' ])): ?>
.header__content .block-search .action.search:hover svg, .header__content a.button.action-search-slideout:hover svg { fill: <?php echo $at_appearance[ 'appearance_header' ][ 'search_icon_color_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_field_bg' ])): ?>
.header__content .header__item-search form input { background: <?php echo $at_appearance[ 'appearance_header' ][ 'search_field_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'search_field_text_color' ])): ?>
.header__content .header__item-search form input { color: <?php echo $at_appearance[ 'appearance_header' ][ 'search_field_text_color' ]; ?>; }
<?php endif; ?>

/* Menu Appearance */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_color' ])): ?>
.slide-out-menu--mobile,
.page-header .ox-megamenu .level0 > .level-top,
.page-header .navigation .level0 > .level-top { color: <?php echo $at_appearance[ 'appearance_header' ][ 'menu_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_bg_hover' ])): ?>
.ox-megamenu .level0 > .level-top:hover, 
.navigation .level0 > .level-top:hover,
.ox-megamenu-navigation > .level0 > .level-top:hover,
.page-header .ox-megamenu .level0 > .level-top:before,
.page-header .navigation .level0 > .level-top:before { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'menu_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_below_bg' ])): ?>
@media only screen and (max-width: 1024px){
	.menu-position--below .header__content{ background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'menu_below_bg' ]; ?>; }
}
.menu-position--below .ox-sticky.sticky.resize .sticky-wrapper,
.header-nav-wide { background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'menu_below_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_color_hover' ])): ?>
.ox-megamenu-navigation > .level0:not(.active):not(.has-active):hover > .level-top,
.header--layout-4.page-header .ox-megamenu > ul > .level0.active > .level-top, 
.header--layout-4.page-header .ox-megamenu > ul > .level0:hover > .level-top,
.page-header .ox-megamenu > ul > .level0:hover > .level-top,
.page-header .ox-megamenu .level0.active > .level-top, 
.page-header .ox-megamenu .level0.has-active > .level-top ,
.header--layout-4.page-header .navigation > ul > .level0.active > .level-top, 
.header--layout-4.page-header .navigation > ul > .level0:hover > .level-top,
.page-header .navigation > ul > .level0:hover > .level-top,
.page-header .navigation .level0.active > .level-top, 
.page-header .navigation .level0.has-active > .level-top { color: <?php echo $at_appearance[ 'appearance_header' ][ 'menu_color_hover' ]; ?>; }
<?php endif; ?>

<?php if( isset($at_appearance[ 'appearance_header' ][ 'menu_letter_spacing' ]) && $at_appearance[ 'appearance_header' ][ 'menu_letter_spacing' ] != '' ): ?>
.page-header .ox-megamenu .level0 > .level-top, 
.page-header .navigation .level0 > .level-top, 
.slide-out-menu--mobile,
.header--layout-4 .minicart-wrapper .action.showcart,
.ox-nav-sections-item-title .ox-nav-sections-item-switch,
.ox-megamenu-navigation > .level0 > .level-top{ letter-spacing:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_letter_spacing' ]; ?>px;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_font_weight' ])): ?>
.page-header .ox-megamenu .level0 > .level-top, 
.page-header .navigation .level0 > .level-top, 
.ox-megamenu-navigation .ox-dropdown--simple .category-item  a,
.slide-out-menu--mobile,
.header--layout-4 .minicart-wrapper .action.showcart,
.ox-nav-sections-item-title .ox-nav-sections-item-switch,
.ox-megamenu-navigation > .level0 > .level-top{ font-weight:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_font_weight' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_font_size' ])): ?>
.page-header .ox-megamenu .level0 > .level-top, 
.page-header .navigation .level0 > .level-top, 
.slide-out-menu--mobile,
.header--layout-4 .minicart-wrapper .action.showcart,
.ox-nav-sections-item-title .ox-nav-sections-item-switch,
.ox-megamenu-navigation > .level0 > .level-top{ font-size:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_font_size' ]; ?>px;}
<?php endif; ?>

/* Mobile menu*/
<?php if( $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_letter_spacing' ] != '' ): ?>
.ox-section-item-content .ox-megamenu-navigation > .level0 > .level-top{ letter-spacing:<?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_letter_spacing' ]; ?>px;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_font_weight' ])): ?>
.ox-section-item-content .ox-megamenu-navigation > .level0 > .level-top{ font-weight:<?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_font_weight' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_font_size' ])): ?>
.ox-section-item-content .ox-megamenu-navigation > .level0 > .level-top{ font-size:<?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_font_size' ]; ?>px;}
<?php endif; ?>

/* Menu Drop Down Appearance */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_menu_text_color' ])): ?>
.ox-megamenu-navigation li > a .ox-menu-arrow:after, 
.ox-megamenu-navigation li > a .ox-menu-arrow:before,
.ox-megamenu-navigation li.parent > a .ox-menu-arrow:after, 
.ox-megamenu-navigation li.parent > a .ox-menu-arrow:before,
.page-header .ox-megamenu .level0 .submenu li.parent > a > .ui-menu-icon:after,
.page-header .ox-megamenu .level0 .submenu li.parent > a > .ui-menu-icon:before,
.page-header .navigation .level0 .submenu li.parent > a > .ui-menu-icon:after,
.page-header .navigation .level0 .submenu li.parent > a > .ui-menu-icon:before  { background: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_text_color' ]; ?>; }


.ox-megamenu-navigation .ox-megamenu-block .links-bg-hover a,
.ox-megamenu-navigation .ox-megamenu-block a.bg-hover,
.ox-megamenu-navigation .ox-megamenu-block .std a,
.ox-section-item-content,
.ox-section-item-content input,
.ox-section-item-content .block-title strong,
.ox-slideout .header.links .logged-in,
.ox-slideout .header.links a:not(.button),
.ox-slideout .switcher .options ul.dropdown a,
.ox-section-item-content .block-customer-login .secondary > a.action,
.ox-megamenu .level0 > .level-top,
.navigation .level0 > .level-top,
.ox-megamenu-navigation a.bg-hover, 
.ox-megamenu-navigation .std a, 
.ox-megamenu-navigation .links-bg-hover a,
.ox-megamenu__dropdown .category-item > a,
.ox-megamenu-navigation h1, .ox-megamenu-navigation h2, .ox-megamenu-navigation h3, .ox-megamenu-navigation h4, .ox-megamenu-navigation h5, .ox-megamenu-navigation h6, 
.ox-megamenu-navigation .h1, .ox-megamenu-navigation .h2, .ox-megamenu-navigation .h3, .ox-megamenu-navigation .h4, .ox-megamenu-navigation .h5, .ox-megamenu-navigation .h6,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item > a,
.ox-megamenu__dropdown,
.page-header .ox-megamenu .level0 .submenu a,
.page-header .navigation .level0 .submenu a { color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_text_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_menu_text_bg_hover' ])): ?>
.ox-megamenu-navigation .ox-megamenu-block .links-bg-hover a:hover,
.ox-megamenu-navigation .ox-megamenu-block a.bg-hover:hover,
.ox-megamenu-navigation .ox-megamenu-block .std a:hover,
.ox-section-item-content .block-customer-login .secondary > a.action:hover,
.ox-nav-sections .ox-megamenu-navigation .category-item.has-active > .level-top, 
.ox-nav-sections .ox-megamenu-navigation .category-item.active > .level-top, 
.ox-nav-sections .ox-megamenu-navigation .category-item.has-active > a, 
.ox-nav-sections .ox-megamenu-navigation .category-item.active > a,
.ox-section-item-content .block-customer-login .secondary > a.action:after,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item > a:hover,
.ox-megamenu__dropdown .category-item:hover > a,
.page-header .ox-megamenu .level0 .submenu a:hover, .page-header .ox-megamenu .level0 .submenu a.ui-state-focus,
.page-header .navigation .level0 .submenu a:hover, .page-header .navigation .level0 .submenu a.ui-state-focus { background: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_text_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_menu_color_hover' ])): ?>
.ox-megamenu-navigation .ox-megamenu-block .links-bg-hover a:hover,
.ox-megamenu-navigation .ox-megamenu-block a.bg-hover:hover,
.ox-megamenu-navigation .ox-megamenu-block .std a:hover,
.ox-nav-sections .ox-megamenu-navigation .category-item.has-active > .level-top, 
.ox-nav-sections .ox-megamenu-navigation .category-item.active > .level-top, 
.ox-nav-sections .ox-megamenu-navigation .category-item.has-active > a, 
.ox-nav-sections .ox-megamenu-navigation .category-item.active > a,
.ox-section-item-content .block-customer-login .secondary > a.action:hover,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item > a:hover,
.ox-megamenu__dropdown .category-item:hover > a,
.page-header .ox-megamenu .level0 .submenu a:hover, .page-header .ox-megamenu .level0 .submenu a.ui-state-focus,
.page-header .navigation .level0 .submenu a:hover, .page-header .navigation .level0 .submenu a.ui-state-focus { color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_color_hover' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_menu_active_color' ])): ?>
.ox-megamenu-navigation .category-item.has-active > .level-top .ox-menu-arrow:before, 
.ox-megamenu-navigation .category-item.active > .level-top .ox-menu-arrow:before, 
.ox-megamenu-navigation .category-item.has-active > a .ox-menu-arrow:before, 
.ox-megamenu-navigation .category-item.active > a .ox-menu-arrow:before, 
.ox-megamenu-navigation .category-item.has-active > .level-top .ox-menu-arrow:after, 
.ox-megamenu-navigation .category-item.active > .level-top .ox-menu-arrow:after, 
.ox-megamenu-navigation .category-item.has-active > a .ox-menu-arrow:after, 
.ox-megamenu-navigation .category-item.active > a .ox-menu-arrow:after{ background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_active_color' ]; ?>; }


.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,
.ox-slideout .switcher.language .options .action.toggle strong span,
.ox-megamenu-navigation .ox-megamenu__dropdown .category-item.active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item.has-active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item.active > a,
.page-header .ox-megamenu .level0 .ox-submenu .active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item.active > a{ color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_active_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_menu_active_bg' ])): ?>
.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,
.ox-slideout .switcher.language .options .action.toggle strong span,
.ox-megamenu-navigation .ox-megamenu__dropdown .category-item.active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item.has-active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item.active > a,
.page-header .ox-megamenu .level0 .ox-submenu .active > a,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item.active > a{ background-color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_menu_active_bg' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_bg' ])): ?>
.page-header .ox-megamenu .level0 .submenu,
.ox-nav-sections-item-content,
.ox-megamenu__dropdown,
.ox-nav-sections,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item > .submenu,
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level1.category-item > .ox-submenu,
.page-header .navigation .level0 .submenu { background: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'submenu_dropdown_bg' ])): ?>
@media (min-width: 1025px) {
.page-header .ox-megamenu .level0 .submenu, .page-header .navigation .level0 .submenu,
.page-header .ox-megamenu .level0 .ox-submenu, .page-header .navigation .level0 .ox-submenu,
.ox-submenu{ background: <?php echo $at_appearance[ 'appearance_header' ][ 'submenu_dropdown_bg' ]; ?>; }
}
<?php endif; ?>

/* Mobile tab */
@media only screen and (max-width: 1024px) {
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_color' ])): ?>
.ox-nav-sections-item-title .ox-nav-sections-item-switch { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_bg' ])): ?>
.ox-nav-sections-item-title:after{ background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_color_hover' ])): ?>
.ox-nav-sections-item-title.active .ox-nav-sections-item-switch { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_color_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_bg_hover' ])): ?>
.ox-nav-sections-item-title.active:after{ background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_tab_bg_hover' ]; ?>; }
<?php endif; ?>
}

<?php if($_helper->getFont( 'menu_font' )): ?>
.ox-slideout .header.links .logged-in,
.ox-slideout .header.links a:not(.button),
.ox-slideout .switcher .options ul.dropdown a,
.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,
.slide-out-menu--mobile,
.ox-nav-sections-item-title .ox-nav-sections-item-switch,
.minicart-wrapper .action.showcart,
.ox-megamenu-navigation .ox-dropdown--simple,
.ox-megamenu .level0 > .level-top, 
.navigation .level0 > .level-top,
.page-header .ox-megamenu .level0 > .level-top, 
.page-header .navigation .level0 > .level-top,
.page-header .ox-megamenu .level0 .ox-submenu,
.ox-megamenu-navigation .ox-megamenu__dropdown .ox-megamenu__categories .level1.category-item > a{ font-family: '<?php echo $_helper->getFont( 'menu_font' ); ?>', 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'dropdown_3rd_color' ])): ?>
.ox-dropdown--megamenu > .ox-megamenu__dropdown .level2.category-item > a { color: <?php echo $at_appearance[ 'appearance_header' ][ 'dropdown_3rd_color' ]; ?>; }
<?php endif; ?>
<?php if($at_appearance[ 'appearance_header' ][ 'menu_drop_letter_spacing' ] != '' ): ?>
.page-header .ox-megamenu .level0 .ox-submenu .category-item > a,
.ox-megamenu-navigation .ox-dropdown--simple .category-item  a,
.ox-slideout .header.links .logged-in,
.ox-slideout .header.links a:not(.button),
.ox-slideout .switcher .options ul.dropdown a,
.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,
.ox-megamenu-navigation .ox-megamenu__dropdown .ox-megamenu__categories .level1.category-item > a { letter-spacing:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_drop_letter_spacing' ]; ?>px;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_drop_font_weight' ])): ?>
.page-header .ox-megamenu .level0 .ox-submenu .category-item > a,
.ox-megamenu-navigation .ox-dropdown--simple .category-item  a,
.ox-slideout .header.links .logged-in,
.ox-slideout .header.links a:not(.button),
.ox-slideout .switcher .options ul.dropdown a,
.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,

.ox-megamenu-navigation .ox-megamenu__dropdown .ox-megamenu__categories .level1.category-item > a { font-weight:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_drop_font_weight' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'menu_drop_font_size' ])): ?>
.page-header .ox-megamenu .level0 .ox-submenu .category-item > a,
.ox-megamenu-navigation .ox-dropdown--simple .category-item  a,
.ox-slideout .header.links .logged-in,
.ox-slideout .header.links a:not(.button),
.ox-slideout .switcher .options ul.dropdown a,
.ox-slideout .switcher .options .action.toggle strong span,
.ox-slideout .switcher .options .action.toggle strong,
.ox-megamenu-navigation .ox-megamenu__dropdown .ox-megamenu__categories .level1.category-item > a { font-size:<?php echo $at_appearance[ 'appearance_header' ][ 'menu_drop_font_size' ]; ?>px;}
<?php endif; ?>

/* Mobile Menu Toggle */
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_border' ])): ?>
.ox-section-item-content input,
.inputs-style--underlined .ox-section-item-content input,
.ox-section-item-content input[type="text"], 
.ox-section-item-content input[type="password"], 
.ox-section-item-content input[type="url"], 
.ox-section-item-content input[type="tel"], 
.ox-section-item-content input[type="search"], 
.ox-section-item-content input[type="number"], 
.ox-section-item-content input[type="datetime"], 
.ox-section-item-content input[type="email"], 
.ox-section-item-content select, 
.ox-section-item-content textarea,
.inputs-style--underlined .ox-section-item-content input[type="text"], 
.inputs-style--underlined .ox-section-item-content input[type="password"], 
.inputs-style--underlined .ox-section-item-content input[type="url"], 
.inputs-style--underlined .ox-section-item-content input[type="tel"], 
.inputs-style--underlined .ox-section-item-content input[type="search"], 
.inputs-style--underlined .ox-section-item-content input[type="number"], 
.inputs-style--underlined .ox-section-item-content input[type="datetime"], 
.inputs-style--underlined .ox-section-item-content input[type="email"], 
.inputs-style--underlined .ox-section-item-content select, 
.inputs-style--underlined .ox-section-item-content textarea { border-color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_border' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_border_hover' ])): ?>
.ox-section-item-content input:hover,
.inputs-style--underlined .ox-section-item-content input:hover,
.ox-section-item-content input[type="text":hover], 
.ox-section-item-content input[type="password"]:hover, 
.ox-section-item-content input[type="url"]:hover, 
.ox-section-item-content input[type="tel"]:hover, 
.ox-section-item-content input[type="search"]:hover, 
.ox-section-item-content input[type="number"]:hover, 
.ox-section-item-content input[type="datetime"]:hover, 
.ox-section-item-content input[type="email"]:hover, 
.ox-section-item-content select:hover, 
.ox-section-item-content textarea:hover,
.inputs-style--underlined .ox-section-item-content input[type="text"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="password"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="url"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="tel"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="search"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="number"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="datetime"]:hover, 
.inputs-style--underlined .ox-section-item-content input[type="email"]:hover, 
.inputs-style--underlined .ox-section-item-content select:hover, 
.inputs-style--underlined .ox-section-item-content textarea:hover,
.ox-section-item-content input:focus,
.inputs-style--underlined .ox-section-item-content input:focus,
.ox-section-item-content input[type="text"]:focus, 
.ox-section-item-content input[type="password"]:focus, 
.ox-section-item-content input[type="url"]:focus, 
.ox-section-item-content input[type="tel"]:focus, 
.ox-section-item-content input[type="search"]:focus, 
.ox-section-item-content input[type="number"]:focus, 
.ox-section-item-content input[type="datetime"]:focus, 
.ox-section-item-content input[type="email"]:focus, 
.ox-section-item-content select:focus, 
.ox-section-item-content textarea:focus,
.inputs-style--underlined .ox-section-item-content input[type="text"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="password"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="url"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="tel"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="search"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="number"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="datetime"]:focus, 
.inputs-style--underlined .ox-section-item-content input[type="email"]:focus, 
.inputs-style--underlined .ox-section-item-content select:focus, 
.inputs-style--underlined .ox-section-item-content textarea:focus { border-color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_border_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_text_color' ])): ?>
.ox-section-item-content input { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_text_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_bg' ])): ?>
.ox-section-item-content input,
.inputs-style--underlined .ox-section-item-content input,
.ox-section-item-content input[type="text"], 
.ox-section-item-content input[type="password"], 
.ox-section-item-content input[type="url"], 
.ox-section-item-content input[type="tel"], 
.ox-section-item-content input[type="search"], 
.ox-section-item-content input[type="number"], 
.ox-section-item-content input[type="datetime"], 
.ox-section-item-content input[type="email"], 
.ox-section-item-content select, 
.ox-section-item-content textarea,
.inputs-style--underlined .ox-section-item-content input[type="text"], 
.inputs-style--underlined .ox-section-item-content input[type="password"], 
.inputs-style--underlined .ox-section-item-content input[type="url"], 
.inputs-style--underlined .ox-section-item-content input[type="tel"], 
.inputs-style--underlined .ox-section-item-content input[type="search"], 
.inputs-style--underlined .ox-section-item-content input[type="number"], 
.inputs-style--underlined .ox-section-item-content input[type="datetime"], 
.inputs-style--underlined .ox-section-item-content input[type="email"], 
.inputs-style--underlined .ox-section-item-content select, 
.inputs-style--underlined .ox-section-item-content textarea { background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_input_bg' ]; ?>; }
<?php endif; ?>

 <?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_text' ])): ?>
.ox-section-item-content .block-new-customer { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_text' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_bg' ])): ?>
.ox-section-item-content .block-new-customer { background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_title' ])): ?>
.ox-section-item-content .block-new-customer .block-title strong { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_mobile_account_new_title' ]; ?>; }
<?php endif; ?>
 
/* Mobile Menu Toggle */
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_bg' ])): ?>
.slide-out-menu--mobile { background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_text' ])): ?>
.slide-out-menu--mobile { color: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_text' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_icon' ])): ?>
.slide-out-menu--mobile .hamburger-menu-icon-small span { background: <?php echo $at_appearance[ 'appearance_header_mobile' ][ 'menu_toggle_icon' ]; ?>; }
<?php endif; ?>

/* Overlay Search */
<?php if(!empty($at_appearance[ 'appearance_modals' ][ 'overlay_bg' ])): ?>
.ox-overlay .header__search-wrapper { background: <?php echo $at_appearance[ 'appearance_modals' ][ 'overlay_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_modals' ][ 'overlay_text_color' ])): ?>
.ox-overlay .header__search-wrapper form input,
/*.ox-overlay .header__search-wrapper form .input-focused .label,*/
.ox-overlay .header__search-wrapper { color: <?php echo $at_appearance[ 'appearance_modals' ][ 'overlay_text_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_modals' ][ 'overlay_accents' ])): ?>
.animated-text--masked:after,
.ox-overlay .header__search-wrapper form .flashing-cursor { background: <?php echo $at_appearance[ 'appearance_modals' ][ 'overlay_accents' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_modals' ][ 'overlay_search_text' ])): ?>
.ox-overlay .header__search-wrapper .animated-text--masked .inner,
.ox-overlay .header__search-wrapper form .label { color: <?php echo $at_appearance[ 'appearance_modals' ][ 'overlay_search_text' ]; ?>; }
<?php endif; ?>

/* Login Page Background */
<?php 
if ( isset( $at_appearance['login_page']['login_page_image'] ) && ! empty( $at_appearance['login_page']['login_page_image'] ) ) {
	echo '.multishipping-checkout-login .page-main, .customer-account-login .page-main, .customer-account-forgotpassword .page-main { background-image: url(' . $_helper->getBaseMediaUrl( Olegnax\Athlete2\Model\Config\Backend\Image\Logo::UPLOAD_DIR ) . "/" . $at_appearance['login_page']['login_page_image'] . '); }';
} ?>
<?php if(!empty($at_appearance[ 'login_page' ][ 'login_page_bg_color' ])): ?>
.multishipping-checkout-login .page-main, .customer-account-login .page-main, .customer-account-forgotpassword .page-main { background-color: <?php echo $at_appearance[ 'login_page' ][ 'login_page_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'login_page' ][ 'login_page_create_account_bg' ])): ?>
.block-new-customer { background-color: <?php echo $at_appearance[ 'login_page' ][ 'login_page_create_account_bg' ]; ?>; }
<?php endif; ?>


/* Create account  */
<?php 
if ( isset( $at_appearance['login_page']['register_page_image'] ) && ! empty( $at_appearance['login_page']['register_page_image'] ) ) {
	echo '.multishipping-checkout-register .page-main, .customer-account-create .page-main { background-image: url(' . $_helper->getBaseMediaUrl( Olegnax\Athlete2\Model\Config\Backend\Image\Logo::UPLOAD_DIR ) . "/" . $at_appearance['login_page']['register_page_image'] . '); }';
} ?>
<?php if(!empty($at_appearance[ 'login_page' ][ 'register_page_bg_color' ])): ?>
.multishipping-checkout-register .page-main,
.customer-account-create .page-main { background-color: <?php echo $at_appearance[ 'login_page' ][ 'register_page_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'login_page' ][ 'register_page_title_color' ])): ?>
.multishipping-checkout-register .page-title-wrapper h1.page-title,
.customer-account-create .page-title-wrapper h1.page-title { color: <?php echo $at_appearance[ 'login_page' ][ 'register_page_title_color' ]; ?>; }
<?php endif; ?>

/* Contact Page */
<?php 
if ( $at_settings['contacts_page'][ 'first_block_type' ] === 'image' && isset( $at_settings['contacts_page']['contacts_page_image'] ) && ! empty( $at_settings['contacts_page']['contacts_page_image'] ) ) {
	echo '.contacts-layout-split .contacts-first-block { background-image: url(' . $_helper->getBaseMediaUrl( Olegnax\Athlete2\Model\Config\Backend\Image\Logo::UPLOAD_DIR ) . "/" . $at_settings['contacts_page']['contacts_page_image'] . '); }';
} ?>

/* Footer */
<?php if($_helper->getFont( 'footer_content_font' ) && $at_appearance[ 'appearance_general' ][ 'footer_google_font_enable' ]): ?>
.footer.content { font-family: '<?php echo $_helper->getFont( 'footer_content_font' ); ?>', 'Roboto', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if($_helper->getFont( 'copyright_content_font' ) && $at_appearance[ 'appearance_general' ][ 'copyright_google_font_enable' ]): ?>
.copyright-footer { font-family: '<?php echo $_helper->getFont( 'copyright_content_font' ); ?>', 'Roboto', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_bg' ])): ?>
.page-footer { background-color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_color' ])): ?>
.footer.content { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_titles' ])): ?>
.footer.content h1, .footer.content h2, .footer.content h3, .footer.content h4, .footer.content h5, .footer.content h6{ color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_titles' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_link' ])): ?>
.footer.content a { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_link' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_link_hover' ])): ?>
.page-footer .switcher:hover .options .action.toggle strong,
.page-footer .switcher .options .action.toggle.active strong,
.footer.content a:hover { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_link_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_link_bg' ])): ?>
.page-footer .switcher:hover .options .action.toggle,
.page-footer .switcher .options .action.toggle.active,
.footer.content a:hover { background-color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_link_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_link_font_size' ])): ?>
.footer.content a:not(.button) { font-size: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_link_font_size' ]; ?>px; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'copyright_bg' ])): ?>
.copyright-footer { background:  <?php echo $at_appearance[ 'appearance_footer' ][ 'copyright_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'copyright_color' ])): ?>
.copyright-footer { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'copyright_color' ]; ?>; }
<?php endif; ?>

/* Footer Switcher */
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_text_color' ])): ?>
.page-footer .switcher .options .action.toggle strong { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_text_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_bg' ])): ?>
.page-footer .switcher .options .action.toggle { background: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_text_hover' ])): ?>
.page-footer .switcher:hover .options .action.toggle strong,
.page-footer .switcher .options .action.toggle.active strong { color: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_text_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_bg_hover' ])): ?>
.page-footer .switcher:hover .options .action.toggle,
.page-footer .switcher .options .action.toggle.active { background: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_font_size' ])): ?>
.page-footer .switcher .options .action.toggle strong { font-size: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_font_size' ]; ?>px; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_drop_font_size' ])): ?>
.page-footer .switcher .options ul.dropdown a { font-size: <?php echo $at_appearance[ 'appearance_footer' ][ 'footer_store_switcher_drop_font_size' ]; ?>px; }
<?php endif; ?>

/* Header Switcher */
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_text_color' ])): ?>
.top-bar .switcher { color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_text_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_bg' ])): ?>
.top-bar .switcher { background: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_text_hover' ])): ?>
.top-bar .switcher:hover { color: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_text_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_bg_hover' ])): ?>
.top-bar .switcher:hover { background: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_bg_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_font_size' ])): ?>
.top-bar .switcher .options .action.toggle strong { font-size: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_font_size' ]; ?>px; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_header' ][ 'top_bar_switcher_drop_font_size' ])): ?>
.top-bar .switcher .options ul.dropdown a { font-size: <?php echo $at_appearance[ 'appearance_header' ][ 'top_bar_switcher_drop_font_size' ]; ?>px; line-height: 1.6; }
<?php endif; ?>

/* Newsletter */

<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_bg' ])): ?>
.footer .block.newsletter { background-color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_color' ])): ?>
.footer .block.newsletter { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_title' ])): ?>
.footer .block.newsletter .title { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_title' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_color' ])): ?>
.footer .block.newsletter .action.primary { color:   <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_bg' ])): ?>
.footer .block.newsletter .action.primary { background-color:  <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_bg' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_hover' ])): ?>
.footer .block.newsletter .action.primary:hover { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_hover' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_hover_bg' ])): ?>
.footer .block.newsletter .action.primary:after { background-color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_button_hover_bg' ]; ?>; }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_bg' ])): ?>
.footer .block.newsletter input { background-color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_bg' ]; ?>; }
.footer .block.newsletter.inputs-style--underlined input { border-color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_bg' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ])): ?>
.footer .block.newsletter input {  color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
.block.newsletter .control:before,
.block.newsletter .field .control:before,
.block.newsletter.inputs-style--underlined .newsletter .control:before,
.block.newsletter.inputs-style--underlined .control:before{ color:  <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
.footer .block.newsletter.inputs-style--underlined input::-webkit-input-placeholder,
.footer .block.newsletter input::-webkit-input-placeholder { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
.footer .block.newsletter.inputs-style--underlined input::placeholder,
.footer .block.newsletter input::placeholder { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
.footer .block.newsletter.inputs-style--underlined input:-ms-input-placeholder,
.footer .block.newsletter input:-ms-input-placeholder { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
.footer .block.newsletter.inputs-style--underlined input::-ms-input-placeholder,
.footer .block.newsletter input::-ms-input-placeholder { color: <?php echo $at_appearance[ 'appearance_footer_newsletter' ][ 'footer_newsletter_input_color' ]; ?>; }
<?php endif; ?>



/* Buttons*/
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'main_button_bg_color' ])): ?>
.ox-toggle.medium-left .ox-toggle-title:hover .toggle-minus,
.cart-summary .actions-toolbar > .primary button,
.footer.content a.athlete2-social-icon, 
.footer.content a:not(.button).athlete2-social-icon, 
.content a.athlete2-social-icon, 
.std a.athlete2-social-icon, 
.athlete2-social-icons > a.athlete2-social-icon, 
a.athlete2-social-icon,
.primary > .action,
.primary > .action:hover,
a.action.primary:hover, .action.primary:hover, .button.primary:hover, a.button.primary:hover, a.button:hover, .button:hover, button:hover, button:focus, button:active,
.ox-banner-animated-text .ox-banner-animated-container .link,
a.action.primary, .action.primary, .button.primary, a.button.primary, 
a.button, .button, button, .cart.table-wrapper .actions-toolbar > .action, .action-gift{ background: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ])): ?>
.cart-summary .actions-toolbar > .primary button,
.footer.content a.athlete2-social-icon, 
.footer.content a:not(.button).athlete2-social-icon, 
.content a.athlete2-social-icon, 
.std a.athlete2-social-icon, 
.athlete2-social-icons > a.athlete2-social-icon, 
a.athlete2-social-icon,
.ox-banner-animated-text .ox-banner-animated-container .link,
.primary > .action,
a.action.primary, .action.primary, .button.primary, a.button.primary, 
a.button, .button, button, .cart.table-wrapper .actions-toolbar > .action, .action-gift{ color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>; }
.primary > .action svg, a.action.primary svg, .action.primary svg, .button.primary svg, a.button.primary svg, a.button svg, .button svg, button svg, .cart.table-wrapper .actions-toolbar > .action svg, .action-gift svg{ fill: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>; }
.ox-toggle.medium-left .ox-toggle-title:hover .toggle-minus span:after, 
.ox-toggle.medium-left .ox-toggle-title:hover .toggle-minus span:before{ background: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>;}
.products-grid .product-item .ox-add-to-cart-loading .action:before{
border-left: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>;
border-right: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>;
border-top: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_color' ]; ?>;
}
<?php endif; ?>
   
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ])): ?>
.opc-block-shipping-information .shipping-information-title .action-edit:hover,
.cart-summary .actions-toolbar > .primary button:hover,
a.action.primary:hover, .action.primary:hover, .button.primary:hover,
.primary > .action:hover,
a.button.primary:hover, a.button:hover, .button:hover, button:hover, button:focus, button:active,
.cart.table-wrapper .actions-toolbar > .action:hover, .action-gift:hover{ color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?> }
a.action.primary:hover svg, 
.action.primary:hover svg, 
.button.primary:hover svg, 
a.button.primary:hover svg,
.primary > .action:hover svg,
a.button:hover svg, 
.button:hover svg, 
button:hover svg, 
.cart.table-wrapper .actions-toolbar > .action:hover svg, 
.action-gift:hover svg{ fill: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?> }
.ox-toggle.medium-left .ox-toggle-title .toggle-minus span:before,
.ox-toggle.medium-left .ox-toggle-title .toggle-minus span:after{background:<?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?> }
.products-grid .product-item .ox-add-to-cart-loading .action:hover:before{
border-left: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?>;
border-right: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?>;
border-top: 2px solid <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_text_hover_color' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'main_button_bg_hover_color' ])): ?>
.ox-toggle.medium-left .ox-toggle-title .toggle-minus,
.cart-summary .actions-toolbar > .primary button:after,
.primary > .action:after,
a.action.primary:after, .action.primary:after, .button.primary:after, 
a.button.primary:after, a.button:after, .button:after, button:after, 
.cart.table-wrapper .actions-toolbar > .action:after, .action-gift:after{ background-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_bg_hover_color' ]; ?> }
<?php endif; ?>
<?php if($_helper->getFont( 'button_font' )): ?>
.product.data.items > .item.title > .switch,
.ox-banner-medium .ox-banner__text-container .link,
.ox-banner-animated-text .ox-banner-animated-container .link,
.ox-banner .link,
.block-cart-failed .action.continue, .cart-container .form-cart .action.continue,
a.action.primary, .action.primary, .action.secondary, .secondary > a.action, 
.button.secondary, .button.primary, a.button.secondary, a.button.primary, a.button, .primary > .action,
.button, button, .cart.table-wrapper .actions-toolbar > .action, .action-gift {	font-family: '<?php echo $_helper->getFont( 'button_font' ); ?>', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
<?php endif; ?>
<?php if($at_appearance[ 'appearance_buttons' ][ 'main_button_letterspacing' ] != ''): ?>
.product.data.items > .item.title > .switch,
.ox-banner-medium .ox-banner__text-container .link,
.ox-banner-animated-text .ox-banner-animated-container .link,
.minicart-items .update-cart-item,
.ox-banner .link,
.block-cart-failed .action.continue, .cart-container .form-cart .action.continue,
a.action.primary, .action.primary, .action.secondary, .secondary > a.action, 
.button.secondary, .button.primary, a.button.secondary, a.button.primary, a.button, .primary > .action,
.button, button, .cart.table-wrapper .actions-toolbar > .action, .action-gift {	letter-spacing: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_letterspacing' ]; ?>px }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'main_button_font_weight' ])): ?>
.product.data.items > .item.title > .switch,
.ox-banner-medium .ox-banner__text-container .link,
.ox-banner-animated-text .ox-banner-animated-container .link,
.ox-banner .link,
.block-cart-failed .action.continue, .cart-container .form-cart .action.continue,
a.action.primary, .action.primary, .action.secondary, .secondary > a.action, 
.button.secondary, .button.primary, a.button.secondary, a.button.primary, a.button, .primary > .action,
.button, button, .cart.table-wrapper .actions-toolbar > .action, .action-gift { font-weight: <?php echo $at_appearance[ 'appearance_buttons' ][ 'main_button_font_weight' ]; ?>}
<?php endif; ?>


/* Naked button */
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'naked_button_bg_hover_color' ])): ?>
a.action.primary.naked:after, .action.primary.naked:after, .button.primary.naked:after, 
a.button.primary.naked:after, a.button.naked:after, .button.naked:after, button.naked:after, 
.cart.table-wrapper .actions-toolbar > .action.naked:after, .action-gift.naked:after{ background-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'naked_button_bg_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'naked_button_text_color' ])): ?>
.login-container .block .secondary > a.action,
.opc-wrapper .form-login .actions-toolbar .secondary a.action,
.block-authentication .actions-toolbar > .secondary > a.action,
a.action.primary.naked, .action.primary.naked, .button.primary.naked, a.button.primary.naked, 
a.button.naked, .button.naked, button.naked, .cart.table-wrapper .actions-toolbar > .action.naked, .action-gift.naked { color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'naked_button_text_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'naked_button_text_hover_color' ])): ?>
a.action.primary.naked:hover, .action.primary.naked:hover, .button.primary.naked:hover, 
.opc-wrapper .form-login .actions-toolbar .secondary a.action:hover,
.block-authentication .actions-toolbar > .secondary > a.action:hover,
a.button.primary.naked:hover, a.button.naked:hover, .button.naked:hover, button.naked:hover, 
.cart.table-wrapper .actions-toolbar > .action.naked:hover, .action-gift.naked:hover { color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'naked_button_text_hover_color' ]; ?> }
<?php endif; ?>

/* Secondary button */
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'second_button_text_color' ])): ?>
.ui-dialog.popup .action.close:before,
#ox_quickview_wrapper .ox-overlay-close-btn span:before, #ox_quickview_wrapper .ox-overlay-close-btn span:after,
.modal-custom .action-close:before, .modal-popup .action-close:before, .modal-slide .action-close:before,
.abs-remove-button-for-blocks:before, .sidebar .action.delete:before, .block-compare .action.delete:before,
.filter-current .action.remove:before,
.account .box-actions .action,
.block-cart-failed .action.clear, .cart-container .form-cart .action.clear,
.block-cart-failed .action.update, .cart-container .form-cart .action.update,
.block-cart-failed .action.continue, .cart-container .form-cart .action.continue,
.button.secondary, a.button.secondary, .action.secondary, .action-secondary, button.action-secondary, 
button.action.secondary, .secondary > a.action, .cart.table-wrapper .actions-toolbar > .action.action-secondary, 
.table-comparison .action.towishlist, .table-comparison .action.tocart,
.table-comparison .action.towishlist:before, .table-comparison .action.tocart:before,
.table-comparison .cell.remove .action.delete:before,
.cart.table-wrapper .actions-toolbar > .action.action.secondary, .action-gift.action-secondary, .action-gift.action.secondary { color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'second_button_text_color' ]; ?>; }
<?php endif; ?>
   
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'second_button_text_hover_color' ])): ?>
#ox_quickview_wrapper .ox-overlay-close-btn:hover span:before, #ox_quickview_wrapper .ox-overlay-close-btn:hover span:after { background-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'second_button_text_hover_color' ]; ?> }
.modal-custom .action-close:focus:before, .modal-popup .action-close:focus:before, .modal-slide .action-close:focus:before, 
.modal-custom .action-close:hover:before, .modal-popup .action-close:hover:before, .modal-slide .action-close:hover:before,
.ui-dialog.popup .action.close:hover:before,
.abs-remove-button-for-blocks:hover:before, .sidebar .action.delete:hover:before, .block-compare .action.delete:hover:before,
.filter-current .action.remove:hover:before,
.account .box-actions .action:hover,
.abs-shopping-cart-items .action.clear:hover, .block-cart-failed .action.clear:hover, .cart-container .form-cart .action.clear:hover,
.abs-shopping-cart-items .action.update:hover, .block-cart-failed .action.update:hover, .cart-container .form-cart .action.update:hover,
.abs-shopping-cart-items .action.continue:hover, .block-cart-failed .action.continue:hover, .cart-container .form-cart .action.continue:hover,
.button.secondary:hover, a.button.secondary:hover, .action.secondary:hover, .action-secondary:hover, 
button.action-secondary:hover, button.action.secondary:hover, .secondary > a.action:hover, 
.login-container .block .secondary > a.action:hover,
.cart.table-wrapper .actions-toolbar > .action.action-secondary:hover, .cart.table-wrapper .actions-toolbar > .action.action.secondary:hover, 
.table-comparison .action.towishlist:hover:before, .table-comparison .action.tocart:hover:before,
.table-comparison .action.towishlist:hover, .table-comparison .action.tocart:hover,
.table-comparison .cell.remove .action.delete:hover:before,
.action-gift.action-secondary:hover, .action-gift.action.secondary:hover{ color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'second_button_text_hover_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'second_button_bg_color' ])): ?>
.ui-dialog.popup .action.close,
#ox_quickview_wrapper .ox-overlay-close-btn,
.modal-custom .action-close, .modal-popup .action-close, .modal-slide .action-close,
.sidebar .action.delete, .block-compare .action.delete,
.filter-current .action.remove:before,
.account .box-actions .action,
.block-cart-failed .action.clear, .cart-container .form-cart .action.clear,
.block-cart-failed .action.update, .cart-container .form-cart .action.update,
.block-cart-failed .action.continue, .cart-container .form-cart .action.continue,
.button.secondary, a.button.secondary, .action.secondary, .action-secondary, button.action-secondary, 
button.action.secondary, .secondary > a.action, .cart.table-wrapper .actions-toolbar > .action.action-secondary, 
.table-comparison .action.towishlist, .table-comparison .action.tocart,
.table-comparison .cell.remove .action.delete,
.block-authentication .actions-toolbar > .primary .action,
.block-authentication .actions-toolbar > .primary .action:hover,
.cart.table-wrapper .actions-toolbar > .action.action.secondary, .action-gift.action-secondary, .action-gift.action.secondary { background: <?php echo $at_appearance[ 'appearance_buttons' ][ 'second_button_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'second_button_bg_hover_color' ])): ?>
.ui-dialog.popup .action.close:hover,
#ox_quickview_wrapper .ox-overlay-close-btn:hover,
.modal-custom .action-close:focus, .modal-popup .action-close:focus, .modal-slide .action-close:focus, 
.modal-custom .action-close:hover, .modal-popup .action-close:hover, .modal-slide .action-close:hover,
.sidebar .action.delete:hover:before, .block-compare .action.delete:hover:before,
.filter-current .action.remove:hover:before,
.account .box-actions .action:hover,
.abs-shopping-cart-items .action.clear:after, .block-cart-failed .action.clear:after, .cart-container .form-cart .action.clear:after,
.abs-shopping-cart-items .action.update:after, .block-cart-failed .action.update:after, .cart-container .form-cart .action.update:after,
.abs-shopping-cart-items .action.continue:after, .block-cart-failed .action.continue:after, .cart-container .form-cart .action.continue:after,
.button.secondary:after, a.button.secondary:after, .action.secondary:after, .action-secondary:after, 
button.action-secondary:after, button.action.secondary:after, .secondary > a.action:after, 
.cart.table-wrapper .actions-toolbar > .action.action-secondary:after, .cart.table-wrapper .actions-toolbar > .action.action.secondary:after, 
.table-comparison .action.towishlist:hover, .table-comparison .action.tocart:hover,
.table-comparison .cell.remove .action.delete:hover,
.action-gift.action-secondary:after, .action-gift.action.secondary:after{ background-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'second_button_bg_hover_color' ]; ?> }
<?php endif; ?>


/*Outline Button*/
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'outline_button_border_color' ])): ?>
.primary > .action.outline, 
a.action.primary.outline, 
.action.primary.outline, 
.button.primary.outline, 
a.button.primary.outline, 
a.button.outline, 
.button.outline, 
button.outline{
    border-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'outline_button_border_color' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'outline_button_text_color' ])): ?>
.primary > .action.outline, 
a.action.primary.outline, 
.action.primary.outline, 
.button.primary.outline, 
a.button.primary.outline, 
a.button.outline, 
.button.outline, 
button.outline{
	color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'outline_button_text_color' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'outline_button_border_hover' ])): ?>
.primary > .action.outline:focus, 
a.action.primary.outline:focus, 
.action.primary.outline:focus, 
.button.primary.outline:focus, 
a.button.primary.outline:focus, 
a.button.outline:focus, 
.button.outline:focus, 
button.outline:focus,
.primary > .action.outline:hover, 
a.action.primary.outline:hover, 
.action.primary.outline:hover, 
.button.primary.outline:hover, 
a.button.primary.outline:hover, 
a.button.outline:hover, 
.button.outline:hover, 
button.outline:hover{
    border-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'outline_button_border_hover' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'outline_button_text_hover' ])): ?>
.primary > .action.outline:focus, 
a.action.primary.outline:focus, 
.action.primary.outline:focus, 
.button.primary.outline:focus, 
a.button.primary.outline:focus, 
a.button.outline:focus, 
.button.outline:focus, 
button.outline:focus,
.primary > .action.outline:hover, 
a.action.primary.outline:hover, 
.action.primary.outline:hover, 
.button.primary.outline:hover, 
a.button.primary.outline:hover, 
a.button.outline:hover, 
.button.outline:hover, 
button.outline:hover{
	color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'outline_button_text_hover' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_buttons' ][ 'outline_button_background_hover' ])): ?>
.primary > .action.outline:after, 
a.action.primary.outline:after, 
.action.primary.outline:after, 
.button.primary.outline:after, 
a.button.primary.outline:after, 
a.button.outline:after, 
.button.outline:after, 
button.outline:after{ 
    background-color: <?php echo $at_appearance[ 'appearance_buttons' ][ 'outline_button_background_hover' ]; ?>;
}
<?php endif; ?>


/* Sidebar */

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_bg' ])): ?>
.filter-options,
.filter.block .content,
.account-nav .content,
.sidebar-additional .block { background-color: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_bg' ]; ?> }
<?php endif; ?>

<?php if('' != ($at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_size' ])): ?>
.filter-options,
.filter.block .content,
.account-nav .content { border-width: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_size' ]; ?>px }
.sidebar-additional .block:before { height: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_size' ]; ?>px }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_color' ])): ?>
.filter-options,
.filter.block .content,
.account-nav .content,
.sidebar-additional .block{ border-color: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_color' ]; ?> }
.sidebar-additional .block:before{ background: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_border_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_title_color' ])): ?>
.sidebar-additional .block .block-title > strong,
.filter.block .content dl.options dt,
.filter-options-title{ color: <?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_title_color' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_color' ])): ?>
.sidebar-additional .block.block-recent-posts .item a,
.sidebar-additional .block.block-archive .item a,
.sidebar-additional .block.block-categories li a,
.filter.block .content dl.options dd li a,
.account-nav .item a, .account-nav .item > strong,
.filter-options-content a{color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_color' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_hover_color' ])): ?>
.mana-filter-block .filter-options-content .item.mana-selected.mana-tree-item a, 
.mana-filter-block .filter-options-content .item.mana-selected a, 
.mana-filter-block .filter-options-content .item.mana-selected.mana-tree-item .label, 
.mana-filter-block .filter-options-content .item.mana-selected .label,
.sidebar-additional .block.block-recent-posts .item a:hover,
.sidebar-additional .block.block-archive .item a:hover,
.sidebar-additional .block.block-categories li a:hover,
.filter.block .content dl.options dd li a:hover,
.account-nav .item.current a, .account-nav .item.current strong,
.account-nav .item a:hover,
.filter-options-title:hover .toggle-minus span:after, 
.filter-options-title:hover .toggle-minus span:before{ background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_hover_color' ]; ?> }
.filter-options-content a:hover{color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_hover_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_hover_bg' ])): ?>
.mana-filter-block .filter-options-content .item.mana-selected.mana-tree-item a, 
.mana-filter-block .filter-options-content .item.mana-selected a, 
.mana-filter-block .filter-options-content .item.mana-selected.mana-tree-item .label, 
.mana-filter-block .filter-options-content .item.mana-selected .label,
.sidebar-additional .block.block-recent-posts .item a:hover,
.sidebar-additional .block.block-archive .item a:hover,
.sidebar-additional .block.block-categories li a:hover,
.filter.block .content dl.options dd li a:hover,
.filter-options-title:hover .toggle-minus,
.account-nav .item.current a, .account-nav .item.current strong,
.account-nav .item a:hover,
.filter-options-content a:hover{background-color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_hover_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'filter_buttom_counter_bg_color' ])): ?>
.filter-current-count {background-color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'filter_buttom_counter_bg_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'filter_buttom_counter_text_color' ])): ?>
.filter-current-count {color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'filter_buttom_counter_text_color' ]; ?> }
<?php endif; ?>


/* Layered Navigation */

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'layered_navigation_loader_overlay_bg' ])): ?>
.ox-product-nav { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'layered_navigation_loader_overlay_bg' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'scroll_loader_color' ])): ?>
.ox-product-scroll.ox-product-scroll__loader--theme.ox-product-scroll__type--button .ox-product-scroll__button:before { background-color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'scroll_loader_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_active_color' ])): ?>
.filter-options-content .ox-seleted-item .label, 
.filter-options-content .ox-seleted-item a { color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_active_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_active_bg' ])): ?>
.filter-options-content .ox-seleted-item .label, 
.filter-options-content .ox-seleted-item a { background-color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_links_active_bg' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_item_checkbox_color' ])): ?>
.filter-options-content .item .ox-checkbox { color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_item_checkbox_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'sidebar_item_active_checkbox_color' ])): ?>
.filter-options-content .ox-seleted-item.item .ox-checkbox, 
.filter-options-content .ox-seleted-item.item .ox-checkbox { color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'sidebar_item_active_checkbox_color' ]; ?> }
<?php endif; ?>

/* Price Slider */
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_handle_color' ])): ?>
.filter-options-content .ui-slider .ui-slider-handle,
.filter-options-content .ox-price-slider .ui-slider-handle,
.filter-options-content .noUi-handle { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_handle_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_handle_hover_color' ])): ?>
.filter-options-content .ui-slider .ui-slider-handle:hover,
.filter-options-content .ox-price-slider .ui-slider-handle:hover,
.filter-options-content .noUi-handle:hover { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_handle_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_line_color' ])): ?>
.filter-options-content .ui-slider, 
.filter-options-content .ox-price-slider { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_line_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_line_active_color' ])): ?>
.filter-options-content .ui-slider .ui-slider-range,
.filter-options-content .ox-price-slider .ui-slider-range,
.filter-options-content .noUi-connect { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_line_active_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_tooltip_bg' ])): ?>
.filter-options-content .noUi-tooltip { background:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_tooltip_bg' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_sidebar' ][ 'price_slider_tooltip_text' ])): ?>
.filter-options-content .noUi-tooltip { color:<?php echo $at_appearance[ 'appearance_sidebar' ][ 'price_slider_tooltip_text' ]; ?> }
<?php endif; ?>



/* Reviews */
<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_rating_color' ])): ?>
.extended-review-summary .ratings-count .rating-result:before,
.extended-review-summary-wrapper .number-of-ratings .rating-result:before { background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_rating_color' ]; ?> }

.review-control-vote:before,
.review-list .rating-summary .rating-result:before,
.rating-summary .rating-result:before{ color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_rating_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_rating_active_color' ])): ?>
.extended-review-summary .ratings-count .rating-result span:before,
.extended-review-summary-wrapper .number-of-ratings .rating-result span:before { background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_rating_active_color' ]; ?> }

.review-control-vote label:before,
.review-list .rating-summary .rating-result > span:before,
.rating-summary .rating-result > span:before{ color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_rating_active_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_small_rating_bg' ])): ?>
.product-info-main .product-reviews-summary .rating-summary{ background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_small_rating_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_bg' ])): ?>
.extended-review-summary,
.fieldset > .review-field-ratings.field:not(.choice), 
.review-field-ratings{ background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_text' ])): ?>
.review-fields-wrapper{ color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_text' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_bg' ])): ?>
.review-fields-wrapper{ background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_text' ])): ?>
.extended-review-summary,
.fieldset > .review-field-ratings.field:not(.choice), 
.fieldset > .review-field-ratings.field:not(.choice) label,
.review-field-ratings{ color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_text' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_rating' ])): ?>
.extended-review-summary .ratings-count .rating-result:before { background-color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_rating' ]; ?> }
.review-field-ratings .review-control-vote:before { color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_top_rating' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_reviews' ][ 'reviews_block_text_big' ])): ?>
.extended-review-summary .ratings-value { color:<?php echo $at_appearance[ 'appearance_reviews' ][ 'reviews_block_text_big' ]; ?> }
<?php endif; ?>

/* Toolabr */

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_background' ])): ?>
.toolbar-products { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_background' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_text' ])): ?>
.toolbar-products { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_text' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_color' ])): ?>
.toolbar-products .sorter-action svg,
.toolbar-products .modes svg{ fill: <?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_color' ]; ?>}
.js-toolbar-switch:after,
.js-toolbar-switch { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_hover_color' ])): ?>
.toolbar-products .sorter-action:hover svg,
.toolbar-products .modes-mode.active svg, .toolbar-products .modes-mode:hover svg{ fill: <?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_hover_color' ]; ?>}
.js-toolbar-switch:hover:after,
.js-toolbar-switch:hover { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_bg' ])): ?>
.sorter-action,
.js-toolbar-switch,
.modes-mode { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_hover_bg' ])): ?>
.sorter-action:hover,
.js-toolbar-switch:hover,
.modes-mode.active, .modes-mode:hover { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_icon_hover_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_progress_line_color' ])): ?>
.ox-product-scroll__amount .amount-count-line,
.toolbar-amount .amount-count-line { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_progress_line_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_progress_line_color_active' ])): ?>
.ox-product-scroll__amount .amount-count-line span,
.toolbar-amount .amount-count-line span { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_progress_line_color_active' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_dropdown_bg' ])): ?>
.js-toolbar-dropdown { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_dropdown_bg' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_color' ])): ?>
.js-toolbar-dropdown { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_hover_color' ])): ?>
.js-toolbar-dropdown > div:hover { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_hover_bg' ])): ?>
.js-toolbar-dropdown > div:hover { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_link_hover_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color' ])): ?>
.pages .action.previous:before, .pages .action.next:before, .pages .action.previous:after, .pages .action.next:after{ background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color' ]; ?> }
.pages a.page, .pages a.page:visited { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color_hover' ])): ?>
.pages .action.previous:hover:before, .pages .action.next:hover:before, .pages .action.previous:hover:after, .pages .action.next:hover:after{ background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color_hover' ]; ?> }
.pages a.page:hover { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_color_hover' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_bg' ])): ?>
.pages .item:after { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_active_color' ])): ?>
.pages strong.page { color:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_active_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_active_bg' ])): ?>
.pages strong.page { background:<?php echo $at_appearance[ 'appearance_toolbar' ][ 'toolbar_pager_active_bg' ]; ?> }
<?php endif; ?>

/* Product */
<?php if($at_appearance[ 'appearance_product' ][ 'product_name_letter_spacing' ] != '' ): ?>
.product-info-main .page-title-wrapper .page-title { letter-spacing: <?php echo $at_appearance[ 'appearance_product' ][ 'product_name_letter_spacing' ]; ?>px }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_name_font_weight' ])): ?>
.product-info-main .page-title-wrapper .page-title { font-weight: <?php echo $at_appearance[ 'appearance_product' ][ 'product_name_font_weight' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_name_font_size' ])): ?>
.product-info-main .page-title-wrapper .page-title { font-size: <?php echo $at_appearance[ 'appearance_product' ][ 'product_name_font_size' ]; ?>px }
<?php endif; ?>

<?php if($at_appearance[ 'appearance_product' ][ 'product_price_letter_spacing' ] != '' ): ?>
.product-info-main .price-box .price-wrapper, .product-options-bottom .price-box .price-wrapper,
.product-info-main .price-box .price-wrapper .price, .product-options-bottom .price-box .price-wrapper .price{ letter-spacing: <?php echo $at_appearance[ 'appearance_product' ][ 'product_price_letter_spacing' ]; ?>px }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_price_font_weight' ])): ?>
.product-info-main .price-box .price-wrapper, .product-options-bottom .price-box .price-wrapper,
.product-info-main .price-box .price-wrapper .price, .product-options-bottom .price-box .price-wrapper .price{ font-weight: <?php echo $at_appearance[ 'appearance_product' ][ 'product_price_font_weight' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_price_font_size' ])): ?>
.product-info-main .price-box .price-wrapper, .product-options-bottom .price-box .price-wrapper,
.product-info-main .price-box .price-wrapper .price, .product-options-bottom .price-box .price-wrapper .price { font-size: <?php echo $at_appearance[ 'appearance_product' ][ 'product_price_font_size' ]; ?>px }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_price_color' ])): ?>
.price-container .price,
.price-box .price { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_price_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_old_price_color' ])): ?>
.product-info-main .price-box .old-price .price-wrapper span,
.product-info-main .price-box .old-price .price-wrapper .price, 
.product-options-bottom .price-box .old-price .price-wrapper .price,
.old-price .price-box .price,
.old-price .price-wrapper span, 
.old.price .price-wrapper span { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_old_price_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_price_color' ])): ?>
.product-info-main .price-box .price-wrapper .price, 
.product-options-bottom .price-box .price-wrapper .price { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_price_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_special_price_color' ])): ?>
.product-info-main .price-box .special-price .price-wrapper .price, 
.product-options-bottom .price-box .special-price .price-wrapper .price,
.special-price .price, 
.product-item .special-price .price-box .price-container,
.product-item .special-price .price-container .price,
.special-price .price-box .price { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_special_price_color' ]; ?> }
<?php endif; ?>

/* Product Page actions */

<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_actions' ])): ?>
.action.mailto.friend,
.product-info-main .product-social-links .product__social-share, 
.product-options-bottom .product-social-links .product__social-share,
.product-info-main .product__social-share .social-share__action .icon, 
.product-options-bottom .product__social-share .social-share__action .icon,
.product-info-main .product-social-links .product__social-share .social-share__action .icon, 
.product-options-bottom .product-social-links .product__social-share .social-share__action .icon,
.product-info-main .action.tocompare, .product-options-bottom .action.tocompare,
.product-info-main .action.towishlist, .product-options-bottom .action.towishlist, .block-bundle-summary .action.towishlist { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_actions' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_actions_hover' ])): ?>
.action.mailto.friend:hover,
.product-info-main .product-social-links .product__social-share:hover, 
.product-options-bottom .product-social-links .product__social-share:hover,
.product-info-main .product__social-share .social-share__action:hover .icon, 
.product-options-bottom .product__social-share .social-share__action:hover .icon,
.product-info-main .product-social-links .product__social-share .social-share__action:hover .icon, 
.product-options-bottom .product-social-links .product__social-share .social-share__action:hover .icon,
.product-info-main .action.tocompare:hover, .product-options-bottom .action.tocompare:hover,
.product-info-main .action.towishlist:hover, .product-options-bottom .action.towishlist:hover, .block-bundle-summary .action.towishlist:hover { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_actions_hover' ]; ?>  }
<?php endif; ?>


/* Product Tabs */
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_content_text' ])): ?>
.product.data.items > .item.content { color:<?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_content_text' ]; ?> }
@media only screen and (max-width: 639px){
.table-wrapper .table:not(.cart):not(.totals):not(.table-comparison) > tbody > tr td[data-th]:before,
.table-wrapper .table:not(.cart):not(.totals):not(.table-comparison) > tbody > tr th[data-th]:before { color:<?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_content_text' ]; ?> }
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_content_bg' ])): ?>
.catalog-product-view .product.data.items > .item.content { background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_content_bg' ]; ?>  }
<?php endif; ?>
@media (min-width: 1025px){
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_color' ])): ?>
.order-links .item a:visited,
.order-links .item strong, 
.order-links .item a,
.product.data.items > .item.title > .switch:visited,
.product.data.items > .item.title > .switch{ color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_bg' ])): ?>
.order-links .item a:before,
.product.data.items > .item.title > .switch:before{ background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_bg' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_hover_color' ])): ?>
.order-links .item a:focus, 
.order-links .item a:hover,
.product.data.items > .item.title > .switch:focus, 
.product.data.items > .item.title > .switch:hover{ color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_hover_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_active_color' ])): ?>
.order-links .item.current strong,
.product.data.items > .item.title:not(.disabled) > .switch:active, 
.product.data.items > .item.title.active > .switch, 
.product.data.items > .item.title.active > .switch:focus, 
.product.data.items > .item.title.active > .switch:hover{ color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_active_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_active_bg' ])): ?>
.order-links .item.current strong,
.product.data.items > .item.title > .switch:after{ background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_active_bg' ]; ?>  }
<?php endif; ?>
}
@media only screen and (max-width: 1024px){
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_accordion_text_color' ])): ?>
.order-links .item a:visited,
.order-links .item strong, 
.order-links .item a,
.product.data.items > .item.title > .switch,
.product.data.items > .item.title > .switch:visited  { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_accordion_text_color' ]; ?>  }
.product.data.items .item.title > .switch:after, 
.product.data.items .item.title > .switch:before { background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_accordion_text_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_bg' ])): ?>
.order-links .item strong, 
.order-links .item a,
.product.data.items > .item.title > .switch { background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_bg' ]; ?>  }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_active_color' ])): ?>
.product.data.items .item.title.active > .switch:after, 
.product.data.items .item.title.active > .switch:before { background: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_active_color' ]; ?>}

.order-links .item.current strong,
.product.data.items > .item.title:not(.disabled) > .switch:active, 
.product.data.items > .item.title.active > .switch, 
.product.data.items > .item.title.active > .switch:focus, 
.product.data.items > .item.title.active > .switch:hover,
.product.data.items > .item.title > .switch:hover,
.product.data.items .item.title.active > .switch,
.product.data.items .item.title.active > .switch:visited { color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_active_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product' ][ 'product_page_tab_active_bg' ])): ?>
.order-links .item.current strong,
.product.data.items > .item.title:not(.disabled) > .switch:focus, 
.product.data.items > .item.title:not(.disabled) > .switch:hover,
.product.data.items > .item.title:not(.disabled) > .switch:active, 
.product.data.items > .item.title.active > .switch, 
.product.data.items > .item.title.active > .switch:focus, 
.product.data.items > .item.title.active > .switch:hover {background-color: <?php echo $at_appearance[ 'appearance_product' ][ 'product_page_tab_active_bg' ]; ?>  }
<?php endif; ?>
}

/* Product Page Arrows */
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_product_icon_color' ])): ?>
#ox-zoom-cursor span:after, #ox-zoom-cursor span:before,
.fotorama__arr .fotorama__arr__arr:before, 
.fotorama__arr .fotorama__arr__arr:after,
.fotorama__thumb--icon:before,
.fotorama__thumb--icon:after,
.fotorama__fullscreen .fotorama__zoom-in:before, 
.fotorama__fullscreen .fotorama__zoom-in:after,
.fotorama__fullscreen .fotorama__zoom-out:before,
.fotorama--fullscreen .fotorama__fullscreen-icon:after, 
.fotorama--fullscreen .fotorama__fullscreen-icon:before { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_product_icon_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_product_icon_hover_color' ])): ?>
.fotorama__zoom-out:hover:before, 
.fotorama__zoom-out:hover:after, 
.fotorama__zoom-in:hover:before, 
.fotorama__zoom-in:hover:after,
.fotorama__thumb--icon:hover:before,
.fotorama__thumb--icon:hover:after,
.fotorama__arr .fotorama__arr__arr:hover:before, 
.fotorama__arr .fotorama__arr__arr:hover:after ,
.fotorama__fullscreen .fotorama__zoom-in:hover:before, 
.fotorama__fullscreen .fotorama__zoom-in:hover:after,
.fotorama--fullscreen .fotorama__fullscreen-icon:hover:after, 
.fotorama--fullscreen .fotorama__fullscreen-icon:hover:before { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_product_icon_hover_color' ]; ?>  }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_product_bg_color' ])): ?>
 #ox-zoom-cursor span,
.fotorama__fullscreen-icon,
.fotorama__fullscreen .fotorama__zoom-in, 
.fotorama__fullscreen .fotorama__zoom-out,
.fotorama__thumb--icon,
.fotorama__arr .fotorama__arr__arr { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_product_bg_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_product_bg_hover_color' ])): ?>
.fotorama--fullscreen .fotorama__fullscreen-icon:hover, 
.fotorama__zoom-out:hover, 
.fotorama__zoom-in:hover,
.fotorama__thumb--icon:hover,
.fotorama__arr .fotorama__arr__arr:hover{ background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_product_bg_hover_color' ]; ?>  }
<?php endif; ?>

/* Carousel Arrows */
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_icon_color' ])): ?>
.owl-nav button.owl-next span:before, .owl-nav button.owl-prev span:before, 
.owl-nav button.owl-next span:after, .owl-nav button.owl-prev span:after { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_icon_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_bg_color' ])): ?>
.crosssell .owl-carousel .owl-nav button.owl-next, 
.related .owl-carousel .owl-nav button.owl-next, 
.upsell .owl-carousel .owl-nav button.owl-next, 
.crosssell .owl-carousel .owl-nav button.owl-prev, 
.related .owl-carousel .owl-nav button.owl-prev, 
.upsell .owl-carousel .owl-nav button.owl-prev,
.owl-carousel.widget-product-grid .owl-nav button.owl-next, 
.owl-carousel.widget-product-grid .owl-nav button.owl-prev,
.owl-nav button.owl-next, 
.owl-nav button.owl-prev { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_bg_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_icon_hover_color' ])): ?>
.owl-nav button.owl-next:hover span:before, .owl-nav button.owl-prev:hover span:before, 
.owl-nav button.owl-next:hover span:after, .owl-nav button.owl-prev:hover span:after{ background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_icon_hover_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'arrows_bg_hover_color' ])): ?>
.crosssell .owl-carousel .owl-nav button.owl-next:after, 
.related .owl-carousel .owl-nav button.owl-next:after, 
.upsell .owl-carousel .owl-nav button.owl-next:after, 
.crosssell .owl-carousel .owl-nav button.owl-prev:after, 
.related .owl-carousel .owl-nav button.owl-prev:after, 
.upsell .owl-carousel .owl-nav button.owl-prev:after,
.owl-carousel.widget-product-grid .owl-nav button.owl-next:after, 
.owl-carousel.widget-product-grid .owl-nav button.owl-prev:after,
.owl-nav button.owl-next:after, 
.owl-nav button.owl-prev:after{ background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'arrows_bg_hover_color' ]; ?>  }
<?php endif; ?>

/* Dots */
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'carousel_dot_color' ])): ?>
.fotorama__dot,
.owl-carousel .owl-dots button.owl-dot span { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'carousel_dot_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'carousel_dot_active_color' ])): ?>
.fotorama__active .fotorama__dot,
.owl-carousel .owl-dots button.owl-dot:hover span,
.owl-carousel .owl-dots button.owl-dot.active span { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'carousel_dot_active_color' ]; ?>  }
<?php endif; ?>


/* Slideshow */

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_icon_color' ])): ?>
.athlete-slideshow .slide .controls .slide-control span:after, 
.athlete-slideshow .slide .controls .slide-control span:before { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_icon_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_icon_hover_color' ])): ?>
.athlete-slideshow .slide .controls .slide-control:hover span:after,
.athlete-slideshow .slide .controls .slide-control:hover span:before { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_icon_hover_color' ]; ?>  }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_background' ])): ?>
.athlete-slideshow .slide .controls .slide-control { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_background' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_background_hover' ])): ?>
.athlete-slideshow .slide .controls .slide-control:after { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'slideshow_arrow_background_hover' ]; ?>  }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'slideshow_progress_line' ])): ?>
.athlete-slideshow .slide .controls .progress { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'slideshow_progress_line' ]; ?>  }
<?php endif; ?>

/* Banner Slider */
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_icon_color' ])): ?>
.ox-banners-slider__container .owl-nav button.owl-next span:before, 
.ox-banners-slider__container .owl-nav button.owl-prev span:before, 
.ox-banners-slider__container .owl-nav button.owl-next span:after, 
.ox-banners-slider__container .owl-nav button.owl-prev span:after { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_icon_color' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_icon_hover_color' ])): ?>
.ox-banners-slider__container .owl-nav button.owl-next:hover span:before, 
.ox-banners-slider__container .owl-nav button.owl-prev:hover span:before, 
.ox-banners-slider__container .owl-nav button.owl-next:hover span:after, 
.ox-banners-slider__container .owl-nav button.owl-prev:hover span:after{ background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_icon_hover_color' ]; ?>  }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_background' ])): ?>
.ox-banners-slider__container .owl-nav button.owl-next, 
.ox-banners-slider__container .owl-nav button.owl-prev { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_background' ]; ?>  }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_background_hover' ])): ?>
.ox-banners-slider__container .owl-nav button.owl-next:after, 
.ox-banners-slider__container .owl-nav button.owl-prev:after { background-color: <?php echo $at_appearance[ 'appearance_arrows' ][ 'bannerslider_arrow_background_hover' ]; ?>  }
<?php endif; ?>



/* to top */

<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'totop_background' ])): ?>
#toTop { background: <?php echo $at_appearance[ 'appearance_arrows' ][ 'totop_background' ]; ?>  } 
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'totop_background_hover' ])): ?>
#toTop:hover { background:  <?php echo $at_appearance[ 'appearance_arrows' ][ 'totop_background_hover' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'totop_icon_color' ])): ?>
#toTop svg { fill: <?php echo $at_appearance[ 'appearance_arrows' ][ 'totop_icon_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_arrows' ][ 'totop_icon_hover_color' ])): ?>
#toTop:hover svg { fill: <?php echo $at_appearance[ 'appearance_arrows' ][ 'totop_icon_hover_color' ]; ?> }
<?php endif; ?>

/* Footer / Header Banners */
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner_background_color' ])): ?>
.header-banner-below.banner-columns-2 .banner-wrap.first-banner:before,
.header-banner-below.banner-columns-1 { background: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner_background_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner2_background_color' ])): ?>
.header-banner-below.banner-columns-2 .banner-wrap.second-banner:before { background: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner2_background_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner_text_color' ])): ?>
.header-banner-below .banner-wrap p,
.header-banner-below .banner-wrap h1,
.header-banner-below .banner-wrap h2,
.header-banner-below .banner-wrap h3,
.header-banner-below .banner-wrap h4,
.header-banner-below .banner-wrap h5,
.header-banner-below .banner-wrap h6,
.header-banner-below .banner-wrap .h1,
.header-banner-below .banner-wrap .h2,
.header-banner-below .banner-wrap .h3,
.header-banner-below .banner-wrap .h4,
.header-banner-below .banner-wrap .h5,
.header-banner-below .banner-wrap .h6,
.header-banner-below .banner-wrap { color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner_text_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner2_text_color' ])): ?>
.header-banner-below .banner-wrap.second-banner p,
.header-banner-below .banner-wrap.second-banner h1,
.header-banner-below .banner-wrap.second-banner h2,
.header-banner-below .banner-wrap.second-banner h3,
.header-banner-below .banner-wrap.second-banner h4,
.header-banner-below .banner-wrap.second-banner h5,
.header-banner-below .banner-wrap.second-banner h6,
.header-banner-below .banner-wrap.second-banner .h1,
.header-banner-below .banner-wrap.second-banner .h2,
.header-banner-below .banner-wrap.second-banner .h3,
.header-banner-below .banner-wrap.second-banner .h4,
.header-banner-below .banner-wrap.second-banner .h5,
.header-banner-below .banner-wrap.second-banner .h6,
.header-banner-below .banner-wrap.second-banner { color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner2_text_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner_background_color' ])): ?>
.above-footer-banner.banner-columns-2 .banner-wrap.first-banner:before,
.above-footer-banner.banner-columns-1 { background: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner_background_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner2_background_color' ])): ?>
.above-footer-banner.banner-columns-2 .banner-wrap.second-banner:before{ background: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner2_background_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner_background' ])): ?>
.above-footer-banner .banner-wrap p,
.above-footer-banner .banner-wrap h1,
.above-footer-banner .banner-wrap h2,
.above-footer-banner .banner-wrap h3,
.above-footer-banner .banner-wrap h4,
.above-footer-banner .banner-wrap h5,
.above-footer-banner .banner-wrap h6,
.above-footer-banner .banner-wrap .h1,
.above-footer-banner .banner-wrap .h2,
.above-footer-banner .banner-wrap .h3,
.above-footer-banner .banner-wrap .h4,
.above-footer-banner .banner-wrap .h5,
.above-footer-banner .banner-wrap .h6,
.above-footer-banner .banner-wrap{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner_background' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner2_background' ])): ?>
.above-footer-banner .banner-wrap.second-banner p,
.above-footer-banner .banner-wrap.second-banner h1,
.above-footer-banner .banner-wrap.second-banner h2,
.above-footer-banner .banner-wrap.second-banner h3,
.above-footer-banner .banner-wrap.second-banner h4,
.above-footer-banner .banner-wrap.second-banner h5,
.above-footer-banner .banner-wrap.second-banner h6,
.above-footer-banner .banner-wrap.second-banner .h1,
.above-footer-banner .banner-wrap.second-banner .h2,
.above-footer-banner .banner-wrap.second-banner .h3,
.above-footer-banner .banner-wrap.second-banner .h4,
.above-footer-banner .banner-wrap.second-banner .h5,
.above-footer-banner .banner-wrap.second-banner .h6,
.above-footer-banner .banner-wrap.second-banner{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner2_background' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner_link_color' ])): ?>
.header-banner-below .banner-wrap a{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner_link_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner_link_hover_color' ])): ?>
.header-banner-below .banner-wrap a:visited,
.header-banner-below .banner-wrap a:hover,
.header-banner-below .banner-wrap a:active{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner_link_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner2_link_color' ])): ?>
.header-banner-below .banner-wrap.second-banner a{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner2_link_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'header_banner2_link_hover_color' ])): ?>
.header-banner-below .banner-wrap.second-banner a:visited,
.header-banner-below .banner-wrap.second-banner a:hover, 
.header-banner-below .banner-wrap.second-banner a:active{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'header_banner2_link_hover_color' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner_link_color' ])): ?>
.above-footer-banner .banner-wrap a{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner_link_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner_link_hover_color' ])): ?>
.above-footer-banner .banner-wrap a:visited, 
.above-footer-banner .banner-wrap a:hover, 
.above-footer-banner .banner-wrap a:active{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner_link_hover_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner2_link_color' ])): ?>
.above-footer-banner .banner-wrap.second-banner a{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner2_link_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_banners' ][ 'footer_banner2_link_hover_color' ])): ?>
.above-footer-banner .banner-wrap.second-banner a:visited, 
.above-footer-banner .banner-wrap.second-banner a:hover, 
.above-footer-banner .banner-wrap.second-banner a:active{ color: <?php echo $at_appearance[ 'appearance_banners' ][ 'footer_banner2_link_hover_color' ]; ?> }
<?php endif; ?>

/* Cart Page */
<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_color' ])): ?>
.minicart--style-modern .block-minicart .block-content .dropdown-bottom-wrapper .actions > .secondary > a.action { color: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_color' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_bg' ])): ?>
.minicart--style-modern .block-minicart .block-content .dropdown-bottom-wrapper .actions > .secondary > a.action { box-shadow: inset 0 0 0 2px <?php echo $at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_bg' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_color_hover' ])): ?>
.minicart--style-modern .block-minicart .block-content .dropdown-bottom-wrapper .actions > .secondary > a.action:hover { color: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_color_hover' ]; ?> }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_bg_hover' ])): ?>
.minicart--style-modern .block-minicart .block-content .dropdown-bottom-wrapper .actions > .secondary > a.action:after { background-color: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'minicart_viewcart_btn_bg_hover' ]; ?> }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'cart_price_font_size' ])): ?>
table.table-totals tbody tr.grand.totals .price, 
table.totals tbody tr.grand.totals .price,
.minicart--style-modern .header__item-dropdown-content .block-wishlist .amount .price-wrapper:first-child .price, 
.minicart--style-modern .block-minicart .amount .price-wrapper:first-child .price {font-size: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_price_font_size' ]; ?>px}
<?php endif; ?>

<?php if($at_appearance[ 'appearance_cart_page' ][ 'cart_price_letter_spacing' ] != '' ): ?>
table.table-totals tbody tr.grand.totals .price, 
table.totals tbody tr.grand.totals .price,
.minicart--style-modern .header__item-dropdown-content .block-wishlist .amount .price-wrapper:first-child .price, 
.minicart--style-modern .block-minicart .amount .price-wrapper:first-child .price {letter-spacing: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_price_letter_spacing' ]; ?>px }
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'cart_price_font_weight' ])): ?>
table.table-totals tbody tr.grand.totals .price, 
table.totals tbody tr.grand.totals .price,
.minicart--style-modern .header__item-dropdown-content .block-wishlist .amount .price-wrapper:first-child .price, 
.minicart--style-modern .block-minicart .amount .price-wrapper:first-child .price {font-weight: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_price_font_weight' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'cart_price_color' ])): ?>
.opc-estimated-wrapper .estimated-block .estimated-price,
table.table-totals tbody tr.grand.totals .price, 
table.totals tbody tr.grand.totals .price,
.block-wishlist .amount .price-wrapper:first-child .price, 
.block-minicart .amount .price-wrapper:first-child .price {color: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_price_color' ]; ?>} 
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'cart_page_summary_bottom_bg' ])): ?>
.cart-container .checkout-methods-items{ background: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_page_summary_bottom_bg' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_cart_page' ][ 'cart_page_summary_bottom_link' ])): ?>
.cart-container .checkout-methods-items .action.multicheckout { color: <?php echo $at_appearance[ 'appearance_cart_page' ][ 'cart_page_summary_bottom_link' ]; ?>}
<?php endif; ?>


/* Grid */
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_name_font_size' ])): ?>
.products-grid .product-item .product-item-name a { font-size: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_name_font_size' ]; ?>px }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_name_color' ])): ?>
.abs-product-link > a:visited, .product-item-name > a:visited, .product.name a > a:visited,
.product-item-name > a, .product.name a > a,
.product-item .product-item-name a { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_name_color' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_name_hover_color' ])): ?>
.products-grid .product-item:hover .price-box .price-container .price-wrapper, 
.products-grid .product-item:hover .price-box .price-container .price-label,
.product-item:hover .product-item-name a { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_name_hover_color' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_name_bg' ])): ?>
.product-item .minimal-price > .price-label:after,
.product-item .price-box .price-container:after,
.product-item .product-item-name a:after { background-color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_name_bg' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_price_color' ])): ?>
.products-grid .product-item .price-box .minimal-price > .price-label,
.products-grid .product-item .price-box .price-container .price { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_price_color' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_price_font_size' ])): ?>
.products-grid .product-item .price-box .minimal-price > .price-label,
.products-grid .product-item .price-box .price-container .price { font-size: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_price_font_size' ]; ?>px}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_price_hover_color' ])): ?>
.products-grid .product-item:hover .price-box .minimal-price > .price-label,
.products-grid .product-item:hover .price-box .price-container .price { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_price_hover_color' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_price_listview' ])): ?>
.product-item .product-list-view__right-wrapper .price-box .price-container .price { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_price_listview' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_price_listview_font_size' ])): ?>
.product-item .product-list-view__right-wrapper .price-box .price-container .price { font-size: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_price_listview_font_size' ]; ?>px}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_category_link' ])): ?>
.products-list .product-item .ox-product-grid__categories > a,
.products-list .product-item .ox-product-grid__categories > a:hover,
.products-list .product-item .ox-product-grid__categories > a:visited,
.ox-product-grid__categories > a:hover, 
.ox-product-grid__categories > a:visited, 
.ox-product-grid__categories > a { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_category_link' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_overlay_color' ])): ?>
.products-grid .product-item .product-grid-overlay { background-color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_overlay_color' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ])): ?>
.product-items .action.towishlist:before, 
.products.list.items .action.towishlist:before, 
.table-comparison .action.towishlist:before { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ]; ?>}

.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.tocompare svg, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.tocompare svg, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare svg, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare svg,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.primary svg, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.primary svg, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.primary svg, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.primary svg { fill: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ]; ?>}
.products-grid .product-item .ox-add-to-cart-loading .action:before{
border-left: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ]; ?>;
border-right: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ]; ?>;
border-top: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_color' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_actions_bg' ])): ?>
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.primary, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.primary, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.primary, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.primary,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.towishlist, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.towishlist, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.tocompare, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.tocompare, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare { background-color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_bg' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ])): ?>
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover:before, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover:before, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover:before, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover:before { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ]; ?>}
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover svg, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover svg, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover svg, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover svg,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover svg, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover svg, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover svg, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover svg { fill: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ]; ?>}
.products-grid .product-item .ox-add-to-cart-loading .action:hover:before{
border-left: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ]; ?>;
border-right: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ]; ?>;
border-top: 2px solid <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_hover' ]; ?>;
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_actions_bg_hover' ])): ?>
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.tocompare:hover,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.towishlist:hover,
.products-grid__layout-2.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover, 
.products-grid__layout-default.grid .product-grid__image-wrapper .product-item-inner .action.primary:hover, 
.products-grid__layout-2.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover, 
.products-grid__layout-default.products-grid .product-grid__image-wrapper .product-item-inner .action.primary:hover { background-color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_bg_hover' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_actions_indetails' ])): ?>
.product-item .product-list-view__right-wrapper .actions-secondary .action .icon svg { fill: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_indetails' ]; ?>}
.products.list.items .product-list-view__right-wrapper .action.towishlist:before,
.product-item .product-list-view__right-wrapper .actions-secondary .action,
.product-item .product-list-view__right-wrapper .actions-secondary .action:hover,
.products-grid__layout-2.grid .product-item .product-item-details .action.tocompare:before, 
.products-grid__layout-2.products-grid .product-item .product-item-details .action.tocompare:before, 
.products-grid__layout-2.grid .product-item .product-item-details .action.towishlist:before, 
.products-grid__layout-2.products-grid .product-item .product-item-details .action.towishlist:before { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_actions_indetails' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn' ])): ?>
.product-grid__image-wrapper .product-item-inner a.button.quick-view  { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_hover' ])): ?>
.product-grid__image-wrapper .product-item-inner a.button.quick-view:hover { color: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_bg' ])): ?>
.product-grid__image-wrapper .product-item-inner a.button.quick-view { background: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_bg' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_bg_hover' ])): ?>
.product-grid__image-wrapper .product-item-inner a.button.quick-view:hover:after { background: <?php echo $at_appearance[ 'appearance_product_listing' ][ 'listing_quickview_btn_bg_hover' ]; ?>}
<?php endif; ?>


/* CMS Banners */
<?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_color' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .text { color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_color_hover' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .animate-me .text { color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_color_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_bg' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .text { background-color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_bg' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_bg_hover' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .text:after { background-color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_text_bg_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_button_text' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .link { color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_button_text' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_button_bg' ])): ?>
 .ox-banner-animated-text .ox-banner-animated-container .link { background-color: <?php echo $at_appearance[ 'appearance_banners_cms' ][ 'banners_cms_button_bg' ]; ?>}
<?php endif; ?>

 
 /* Blog */
<?php if(!empty($at_appearance[ 'blog_list' ][ 'title_font_size' ])): ?>
@media (min-width: 1025px){
	.post-list.blog-style-classic .post-title {	font-size: <?php echo $at_appearance[ 'blog_list' ][ 'title_font_size' ]; ?>px;}
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'title_letter_spacing' ])): ?>
	.post-list.blog-style-classic .post-title {	letter-spacing: <?php echo $at_appearance[ 'blog_list' ][ 'title_letter_spacing' ]; ?>px;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'big_title_font_size' ])): ?>
@media (min-width: 1025px){
	.post-list.blog-style-modern article.post-style--above-image .post-title, 
	.post-list.blog-style-modern.blog-list--image-top article.post-style--above-image .post-title, 
	.post-list.blog-style-modern.blog-list--first-above-image article:first-child .post-title, 
	.post-list.blog-style-modern.blog-list--above-image article .post-title { font-size: <?php echo $at_appearance[ 'blog_list' ][ 'big_title_font_size' ]; ?>px;}
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'big_title_letter_spacing' ])): ?>
.post-list.blog-style-modern article.post-style--above-image .post-title, 
.post-list.blog-style-modern.blog-list--image-top article.post-style--above-image .post-title, 
.post-list.blog-style-modern.blog-list--first-above-image article:first-child .post-title, 
.post-list.blog-style-modern.blog-list--above-image article .post-title {	letter-spacing: <?php echo $at_appearance[ 'blog_list' ][ 'big_title_letter_spacing' ]; ?>px;}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'blog_list' ][ 'title_color' ])): ?>
.post-list.blog-style-classic article .post-title a,
.post-list.blog-style-modern article .post-title a { color: <?php echo $at_appearance[ 'blog_list' ][ 'title_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'title_color_hover' ])): ?>
.post-list.blog-style-classic article:hover .post-title a,
.post-list.blog-style-modern article:hover .post-title a { color: <?php echo $at_appearance[ 'blog_list' ][ 'title_color_hover' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'title_bg_hover' ])): ?>
.post-list.blog-style-classic article:hover .post-title a { background: <?php echo $at_appearance[ 'blog_list' ][ 'title_bg_hover' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'blog_list' ][ 'category_bg_color' ])): ?>
 .post-list.blog-style-modern article .post-categories a { background: <?php echo $at_appearance[ 'blog_list' ][ 'category_bg_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'category_bg_color_hover' ])): ?>
 .post-list.blog-style-modern article .post-categories a:hover { background: <?php echo $at_appearance[ 'blog_list' ][ 'category_bg_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'category_text_color' ])): ?>
 .post-list.blog-style-modern article .post-categories a { color: <?php echo $at_appearance[ 'blog_list' ][ 'category_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'category_text_color_hover' ])): ?>
 .post-list.blog-style-modern article .post-categories a:hover { color: <?php echo $at_appearance[ 'blog_list' ][ 'category_text_color_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'date_bg_color' ])): ?>
 .post-list.blog-style-classic .post-date .inner,
 .post-list.blog-style-modern article .post-image-wrapper .post-posed-date { background: <?php echo $at_appearance[ 'blog_list' ][ 'date_bg_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'date_text_color' ])): ?>
 .post-list.blog-style-classic .post-date .inner,
 .post-list.blog-style-modern article .post-image-wrapper .post-posed-date { color: <?php echo $at_appearance[ 'blog_list' ][ 'date_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'date_bg_color_hover' ])): ?>
 .post-list.blog-style-classic .post-date .hover { background: <?php echo $at_appearance[ 'blog_list' ][ 'date_bg_color_hover' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'date_text_color_hover' ])): ?>
 .post-list.blog-style-classic .post-date .hover { color: <?php echo $at_appearance[ 'blog_list' ][ 'date_text_color_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'social_color' ])): ?>
 .post-list .social-share__content a i { color: <?php echo $at_appearance[ 'blog_list' ][ 'social_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'social_color_hover' ])): ?>
 .post-list .social-share__content a:hover i { color: <?php echo $at_appearance[ 'blog_list' ][ 'social_color_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'readmore_color' ])): ?>
.post-list.blog-style-modern article .post-links > .item { color: <?php echo $at_appearance[ 'blog_list' ][ 'readmore_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'readmore_hover' ])): ?>
.post-list.blog-style-modern article .post-links > .item:hover { border-color: <?php echo $at_appearance[ 'blog_list' ][ 'readmore_hover' ]; ?>}
<?php endif; ?> 
 
<?php if(!empty($at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ])): ?>
	.post-list article .gradient-overlay { 
	<?php if(!empty($at_appearance[ 'blog_list' ][ 'big_post_gradient_color_second' ])){ ?>
	background: -moz-linear-gradient(top, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color_second' ]; ?> 60%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
    background: -webkit-linear-gradient(top, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color_second' ]; ?> 60%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
    background: linear-gradient(to bottom, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color_second' ]; ?> 60%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
	<?php } else { ?>
	background: -moz-linear-gradient(top, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
    background: -webkit-linear-gradient(top, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
    background: linear-gradient(to bottom, rgba(0,0,0,0) 40%, <?php echo $at_appearance[ 'blog_list' ][ 'big_post_gradient_color' ]; ?> 100%);
	<?php } ?>
	}
<?php endif; ?>

/* Blog Post */
<?php if(!empty($at_appearance[ 'blog_post' ][ 'title_font_size' ])): ?>
@media (min-width: 1025px){
.post-view h1.page-title {	font-size: <?php echo $at_appearance[ 'blog_post' ][ 'title_font_size' ]; ?>px;}
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'content_font_size' ])): ?>
@media (min-width: 640px){
.post-view .post-text-hld p,
.post-view .post-text-hld {	font-size: <?php echo $at_appearance[ 'blog_post' ][ 'content_font_size' ]; ?>px;}
}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'content_line_height' ])): ?>
@media (min-width: 640px){
.post-view .post-text-hld p,
.post-view .post-text-hld {	line-height: <?php echo $at_appearance[ 'blog_post' ][ 'content_line_height' ]; ?>px;}
}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'blog_post' ][ 'related_title_font_size' ])): ?>
.post-view .related .post-list article .post-title {	font-size: <?php echo $at_appearance[ 'blog_post' ][ 'related_title_font_size' ]; ?>px;}
<?php endif; ?>


 <?php if(!empty($at_appearance[ 'blog_post' ][ 'meta_text_color' ])): ?>
.post-view .post-meta .item { color: <?php echo $at_appearance[ 'blog_post' ][ 'meta_text_color' ]; ?>}
<?php endif; ?>

 <?php if(!empty($at_appearance[ 'blog_post' ][ 'social_color' ])): ?>
.post-view .social-share__content a i { color: <?php echo $at_appearance[ 'blog_post' ][ 'social_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'social_color_hover' ])): ?>
.post-view .social-share__content a:hover i { color: <?php echo $at_appearance[ 'blog_post' ][ 'social_color_hover' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'progress_color' ])): ?>
.post-view .blog-post-sticky-info .progress-container { background: <?php echo $at_appearance[ 'blog_post' ][ 'progress_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'progess_color_active' ])): ?>
.post-view .blog-post-sticky-info .progress-bar  { background: <?php echo $at_appearance[ 'blog_post' ][ 'progess_color_active' ]; ?>}
<?php endif; ?>

 
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'category_bg_color' ])): ?>
.post-view .post-categories a { background: <?php echo $at_appearance[ 'blog_post' ][ 'category_bg_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'category_bg_color_hover' ])): ?>
.post-view .post-categories a:hover{ background: <?php echo $at_appearance[ 'blog_post' ][ 'category_bg_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'category_text_color' ])): ?>
.post-view .post-categories a { color: <?php echo $at_appearance[ 'blog_post' ][ 'category_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'category_text_color_hover' ])): ?>
.post-view .post-categories a:hover { color: <?php echo $at_appearance[ 'blog_post' ][ 'category_text_color_hover' ]; ?>}
<?php endif; ?>
 
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'tags_bg_color' ])): ?>
.post-view .post-tags a{ background: <?php echo $at_appearance[ 'blog_post' ][ 'tags_bg_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'tags_bg_color_hover' ])): ?>
.post-view .post-tags a:hover { background: <?php echo $at_appearance[ 'blog_post' ][ 'tags_bg_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'tags_text_color' ])): ?>
.post-view .post-tags a { color: <?php echo $at_appearance[ 'blog_post' ][ 'tags_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_post' ][ 'tags_text_color_hover' ])): ?>
.post-view .post-tags a:hover { color: <?php echo $at_appearance[ 'blog_post' ][ 'tags_text_color_hover' ]; ?>}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'blog_post' ][ 'next_prev_color' ])): ?>
.post-view .nextprev-link span { color: <?php echo $at_appearance[ 'blog_post' ][ 'next_prev_color' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'next_prev_color_hover' ])): ?>
.post-view .post-nextprev-hld .nextprev-link:hover .h3 { color: <?php echo $at_appearance[ 'blog_post' ][ 'next_prev_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'next_prev_bg_color_hover' ])): ?>
.post-view .post-nextprev-hld .nextprev-link:hover .h3 { background: <?php echo $at_appearance[ 'blog_post' ][ 'next_prev_bg_color_hover' ]; ?>;}
<?php endif; ?>

<?php if(!empty($at_appearance[ 'blog_post' ][ 'comments_form_bg' ])): ?>
.post-view .block.comments .fb-comments,
.post-view .block.comments .c-replyform { background: <?php echo $at_appearance[ 'blog_post' ][ 'comments_form_bg' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_post' ][ 'comments_left_line' ])): ?>
.post-view .block.comments .c-comment .c-post { border-color: <?php echo $at_appearance[ 'blog_post' ][ 'comments_left_line' ]; ?>}
<?php endif; ?>

/* Blog sidebar */
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'sidebar_tags_bg_color' ])): ?>
.sidebar-additional .block.block-tagclaud a{ background: <?php echo $at_appearance[ 'blog_list' ][ 'sidebar_tags_bg_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'sidebar_tags_bg_color_hover' ])): ?>
.sidebar-additional .block.block-tagclaud a:hover { background: <?php echo $at_appearance[ 'blog_list' ][ 'sidebar_tags_bg_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'sidebar_tags_text_color' ])): ?>
.sidebar-additional .block.block-tagclaud a { color: <?php echo $at_appearance[ 'blog_list' ][ 'sidebar_tags_text_color' ]; ?>}
<?php endif; ?>
 <?php if(!empty($at_appearance[ 'blog_list' ][ 'sidebar_tags_text_color_hover' ])): ?>
.sidebar-additional .block.block-tagclaud a:hover { color: <?php echo $at_appearance[ 'blog_list' ][ 'sidebar_tags_text_color_hover' ]; ?>}
<?php endif; ?>


/* Blog Widget */
<?php if(!empty($at_appearance[ 'blog_list' ][ 'widget_titles_color' ])): ?>
.blog-widget-recent.ox-blog-widget__titles-only .post-list article .post-title a,
.blog-widget-recent.ox-blog-widget__titles-only .post-list article .post-title { color: <?php echo $at_appearance[ 'blog_list' ][ 'widget_titles_color' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'widget_titles_color_hover' ])): ?>
.blog-widget-recent.ox-blog-widget__titles-only .post-list article:hover .post-title a,
.blog-widget-recent.ox-blog-widget__titles-only .post-list article:hover .post-title { color: <?php echo $at_appearance[ 'blog_list' ][ 'widget_titles_color_hover' ]; ?>}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'blog_list' ][ 'widget_titles_bg_hover' ])): ?>
.blog-widget-recent.ox-blog-widget__titles-only .post-list article:hover .post-title { background: <?php echo $at_appearance[ 'blog_list' ][ 'widget_titles_bg_hover' ]; ?>;}
<?php endif; ?>


/* Order */
<?php if(!empty($at_appearance[ 'checkout_page' ][ 'order_tab_background' ])): ?>
.order-details-items { background: <?php echo $at_appearance[ 'checkout_page' ][ 'order_tab_background' ]; ?>;}
<?php endif; ?>
<?php if(!empty($at_appearance[ 'checkout_page' ][ 'order_tab_text_color' ])): ?>
.order-details-items .order-title > strong,
.order-details-items { color: <?php echo $at_appearance[ 'checkout_page' ][ 'order_tab_text_color' ]; ?>;}
<?php endif; ?>

/* Checkout */
<?php 
if ( isset( $at_appearance['checkout_page']['success_page_image'] ) && ! empty( $at_appearance['checkout_page']['success_page_image'] ) ) {
	echo 'body.multishipping-checkout-success, body.checkout-onepage-success { background-image: url(' . $_helper->getBaseMediaUrl( Olegnax\Athlete2\Model\Config\Backend\Image\Logo::UPLOAD_DIR ) . "/" . $at_appearance['checkout_page']['success_page_image'] . '); }';
} ?>
<?php if(!empty($at_appearance[ 'checkout_page' ][ 'success_page_bg_color' ])): ?>
body.multishipping-checkout-success, 
body.checkout-onepage-success { background-color: <?php echo $at_appearance[ 'checkout_page' ][ 'success_page_bg_color' ]; ?>; }
<?php endif; ?>
<?php if(!empty($at_appearance[ 'checkout_page' ][ 'success_page_title_color' ])): ?>
body.multishipping-checkout-success h1.page-title, body.checkout-onepage-success h1.page-title { color: <?php echo $at_appearance[ 'checkout_page' ][ 'success_page_title_color' ]; ?>; }
<?php endif; ?>
/* ================================================================== */
/* CUSTOM CSS */
/* ================================================================== */

<?php if($at_appearance[ 'appearance_custom' ][ 'custom_css_enabled']  && !empty($at_appearance[ 'appearance_custom' ][ 'custom_css_content' ])){
	echo $at_appearance[ 'appearance_custom' ][ 'custom_css_content' ];
}
?>