<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="block block-new-customer">
    
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <h2>New Here?</h2>
        <p class="form-instructions">Registration is for service companies only</p>
        <ul class="benefits">
            <li>Faster checkout</li>
            <li>Save multiple shipping addresses</li>
            <li>View and track orders and more</li>
        </ul>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account - SERVICE COMPANIES ONLY')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
