<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
 
  <td class="wishlist-cell1 customer-wishlist-item-info">
                        <h3 class="product-name">
<!-- <strong class="product-item-name"> -->
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
    
<!-- </strong> -->
</h3>
<span>Sku: <?= $block->escapeHtml($product->getSku()) ?></span>