<?php
$arrowIcon = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" class="sp-svg-16" xml:space="preserve">
                <polygon points="10.8,7 9,8.8 9,3 7,3 7,8.8 5.2,7 4,8.2 7.8,12 8.2,12 12,8.2 "></polygon>
                </svg>';


?>

<div class="toolbar toolbar-products flex-row">
	<div class="flex-left d-flex align-items-center">
		<div class="toolbar-sorter sorter">
			<?php $currentSort = $this->getRequest()->getParam('sort', false);?>
			<div class="js-toolbar-switch">
				<!--<label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label> 
				<?php 
				$_order = __('Created At');
				if($currentSort == 'user')	{
					$_order = __('Added By');
				}
				?>
				<label class="current"><?= $block->escapeHtml(__($_order)) ?></label>-->
				<!--<div class="js-toolbar-dropdown sorter-options" id="sorter" >-->
		            <select name="sorter" data-role="sorter" class="sorter-options">
						<option value="created_at" <?php if (!$currentSort || $currentSort == 'create_at'): ?>selected="selected"<?php endif; ?>>
							<?= $block->escapeHtml(__('Created At')) ?>
			            </option>
						<option value="user" <?php if ($currentSort == 'user'): ?>selected="selected"<?php endif; ?>>
							<?= $block->escapeHtml(__('Added By')) ?>
			            </option>
					</select>
			    <!--</div>-->
			</div>
						
			<?php $sortDirection = $this->getRequest()->getParam('direction', false);  ?>
		    <?php if ($sortDirection != 'asc'): ?>
		        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
		            <?php echo $arrowIcon ?><span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
		        </a>
		    <?php else: ?>
		        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
		            <?php echo $arrowIcon ?><span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
		        </a>
		    <?php endif; ?>
		</div>
	</div>
	
	<div class="flex-right d-flex align-items-center">
		<?php $totalProducts = $block->getTotalNum();?>
		<div class="toolbar-amount" id="toolbar-amount">
		    <div class="amount-wrap"><?php if ($block->getLastPageNum() > 1): ?>
		        <?= $block->escapeHtml(
		            __(
		                'Items %1-%2 of %3',
		                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
		                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
		                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
		            ),
		            ['span']
		        ) ?>
		    <?php elseif ($totalProducts == 1): ?>
		        <?= $block->escapeHtml(__('%1 Item',
		           '<span class="toolbar-number">' . $totalProducts . '</span>'),
		            ['span']
				) ?>
		    <?php else: ?>
		        <?= $block->escapeHtml(__('%1 Items',
		            '<span class="toolbar-number">' . $totalProducts . '</span>'),
		            ['span']
				) ?>
		    <?php endif; ?>
			</div>
			<?php if( $totalProducts > 0 ) { 
				$progress_line = ( $block->getLastNum() / $totalProducts ) * 100; 		
			} else { 
				$progress_line= 0; 		
			}; ?>
			<div class="amount-count-line"><span style="width: <?= $block->escapeHtmlAttr($progress_line) ?>%;"></span></div>
		</div>
		
		<div class="field limiter js-toolbar-switch">
		    <!--<label class="label" for="limiter">
		        <span><?= $block->escapeHtml(__('Show')) ?></span>
					<?php foreach ($block->getAvailableLimit() as $_key => $_limit):
						if ($block->isLimitCurrent($_key)): ?>
		                <span class="current">
		                    <?= $block->escapeHtml($_limit) ?>
		                </span>
		            <?php endif;
					endforeach; ?>
					<span class="limiter-text"><?= $block->escapeHtml(__('per page')) ?></span>
		    </label>-->
			<!--<div id="limiter" class="limiter-options js-toolbar-dropdown">-->
				<select data-role="limiter" class="limiter-options">
				<?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
					<option value="<?= $block->escapeHtmlAttr($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
						selected="selected"<?php endif ?>>
						<?= $block->escapeHtml($_limit) ?>
					</div>
				<?php endforeach; ?>
				</select>
			<!--</div>-->    
		</div>
	</div>
</div>