<?php 
    $slides = $this->getSlides();
    //echo '<pre>'; print_r($slides->getData()); die;
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
    $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
    $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

    <div id="sync1" class="slider owl-carousel">
    <?php foreach($slides as $slide){ ?>
          <div class="item">
            <div class="slide-title">
                <?php 
                    echo $slide->getTitle(); 
                    echo '<a href="' . $slide->getLinkHref() . '" class="link"  >' . $slide->getLinkText() . '<span></span></a>';
                ?>
            </div>
            <div class="clear"></div>
            <img src="<?php echo $mediaUrl.$slide->getImage(); ?>">
        </div>
      <?php } ?>
    </div>
    <div id="sync2" class="navigation-thumbs owl-carousel">
        <?php foreach($slides as $slide){ ?>
            <div class="item">
                <!--<img src="<?php echo $mediaUrl.$slide->getBanner1Img(); ?>" class="img-fluid">-->
            </div>
          <?php } ?>
    </div>




