<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $StockState = $objectManager->get('Magento\CatalogInventory\Model\Stock\StockItemRepository');

    $stockItem = $StockState->get($_product->getId());
	$IsInStock = $stockItem->getIsInStock();

?>
<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($IsInStock) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
