<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
$athlete_search_type = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/header/search_type');
$search_icon = '<span class="search-icon-wrapper"><svg data-name="search-icon-small 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15"><rect x="11.73223" y="10.52513" width="2" height="4.41421" transform="translate(-5.27386 12.73223) rotate(-45)"></rect><path d="M7,0a7,7,0,1,0,7,7A7,7,0,0,0,7,0ZM7,12a5,5,0,1,1,5-5A5,5,0,0,1,7,12Z"></path></svg></span>';
$placeholderText = __('Search');
$input_classes = 'js-input-focus';
if ($athlete_search_type == 'overlay') {
    $input_classes .= ' width-dynamic';
}
?>
<div class="block block-search header__item header__item-search block-search--type-<?= $block->escapeHtmlAttr($athlete_search_type) ?>">
	<div class="block block-content"<?php
    switch ($athlete_search_type) {
        case 'slideout':
        case 'overlay':
            ?> data-role="OXmodal"
			data-mage-init='{"OXmodal":{
				 "triggerTarget":".action-search-slideout",
				 "closeButtonTrigger": ".ox-overlay-close-btn",
				 "overlayClass":"ox-slideout-shadow",
				 "timeout": "1000",
				 "closeOnEscape": true,
				 "closeOnMouseLeave": false,
				 "hoverOpen": false,
				 "type": "<?= $block->escapeHtmlAttr($athlete_search_type) ?>",
				 "positionSlideout":"top",
				 "htmlClass":"ox-fixed"
				 }}'<?php
            break;
    }
    ?>>
		<div class="header__search-wrapper<?=
        !in_array($athlete_search_type, ['slideout', 'overlay']) ? ' ox-move-item ox-move-item-header.search-mini' : '';
        ?>">
			<div class="ox-overlay-close-btn"><span></span></div>
			<?php if ($athlete_search_type == 'overlay') {
            ?>
				<div class="logo__container">
					<?php echo $block->getLayout()->getBlock('logo')->toHtml(); ?>
				</div>
			<?php
        } ?>
			<form class="form minisearch" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">

				<div class="field search">
					<div class="control">
						<div class="flashing-cursor"></div>
						<input id="search"
							   data-mage-init='{"quickSearch":{
							   "formSelector":"#search_mini_form",
							   "url":"<?= $block->escapeUrl($helper->getSuggestUrl()) ?>",
							   "destinationSelector":"#search_autocomplete"}
							   }'
							   type="text"
							   name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
							   value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
							   placeholder="<?= $block->escapeHtmlAttr($placeholderText) ?>"
							   class="input-text <?= $block->escapeHtmlAttr($input_classes) ?>"
							   maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
							   role="combobox"
							   aria-haspopup="false"
							   aria-autocomplete="both"
							   autocomplete="off"
							   aria-expanded="false"/>
						<div id="search_autocomplete" class="search-autocomplete"></div>
						<div class="label animated-text--masked" for="search" data-role="minisearch-label">
							<div class="wrap">
								<span class="inner"><?= $block->escapeHtml($placeholderText) ?></span>
							</div>
						</div>
						<?= $block->getChildHtml() ?>
					</div>
				</div>
				<div class="actions">
					<button type="submit"
							title="<?= $block->escapeHtml(__('Go')) ?>"
							class="action search"
							aria-label="Search"
					>
						<?= $search_icon ?>
						<span><?= $block->escapeHtml(__('Go')) ?></span>
					</button>
				</div>
			</form>
		</div>

	</div>
	<?php if (!in_array($athlete_search_type, ['slideout', 'overlay'])) : ?>
		<div class="block block-content block-content-slideout" data-move-mobile="header.search-mini"
			 style="display:none" data-role="OXmodal"
			 data-mage-init='{"OXmodal":{
			 "triggerTarget":".action-search-slideout",
			 "closeButtonTrigger": ".ox-overlay-close-btn",
			 "overlayClass":"ox-slideout-shadow",
			 "timeout": "1000",
			 "closeOnEscape": true,
			 "closeOnMouseLeave": false,
			 "hoverOpen": false,
			 "type": "slideout",
			 "positionSlideout":"top",
			 "htmlClass":"ox-fixed"
			 }}'>
		</div>
	<?php endif; ?>
	<a class="button action-search-slideout"><?= $search_icon ?></a>
</div>
