<?php
$_helper = $this->helper(\Olegnax\Athlete2\Helper\CssFiles::class);

if ($this->getConfig('athlete2_design/appearance_general/google_font_enable')) {
    ?>
	<link rel="stylesheet" type="text/css" media="all" href="<?= $_helper->getGoogleFontUrl(); ?>"/>
<?php } ?>
	<link rel="stylesheet" type="text/css" media="all"
		  href="<?php echo $_helper->getDynamicCss('settings') . ($this->getConfig('athlete2_design/appearance_custom/dynamic_file_arg_enable') ? '?v=' . $this->getConfig('athlete2_design/appearance_custom/dynamic_file_arg').'.0' : '') ?>"/>
<?php if ($this->getConfig('athlete2_design/appearance_general/fontawesome_enabled')) { ?>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
		  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<?php } ?>