<?php
$elementName = 'product360images' . '[images]';
$formName = 'edit_form';
?>
<div id="<?php echo $this->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"product360gallery":{"template":"#<?php echo $this->getHtmlId() ?>-template"}}'
     data-images="<?php echo $this->escapeHtml($this->getImagesJson()) ?>"
     data-types="<?php echo $this->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getImageTypes()))?>"
    >
<div class="image image-placeholder">
<?php echo $this->getUploaderHtml(); ?>
<div class="product-image-wrapper">
<p class="image-placeholder-text">
<?php /* @escapeNotVerified */ echo __('Browse to find or drag image here'); ?>
</p>
</div>
</div>
<?php foreach ($this->getImageTypes() as $typeData) {
    ?>
        <input name="<?php echo $this->escapeHtml($typeData['name']) ?>"
               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
               class="image-<?php echo $this->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?php echo $this->escapeHtml($typeData['value']) ?>"/>
    <?php
}?>


    <script id="<?php echo $this->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   class="position"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][file]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.file %>"/>
        <input type="hidden" name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][url]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.url %>"/>
            <input type="hidden" name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][path]" data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>" value="<%- data.path %>" />
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][value_id]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.value_id %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][label]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][disabled]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.disabled %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="image"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value=""
                   class="is-removed"/>

            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?php /* @escapeNotVerified */ echo __('Delete image') ?>">
                    <span>
                        <?php /* @escapeNotVerified */ echo __('Delete image') ?>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?php /* @escapeNotVerified */ echo __('Hidden') ?></span></div>
            </div>


            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                  <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php
                foreach ($this->getImageTypes() as $typeData) {
                    ?>
                    <li data-role-code="<?php /* @escapeNotVerified */ echo $this->escapeHtml($typeData['code'])?>" class="item-role item-role-<?php /* @escapeNotVerified */ echo $this->escapeHtml($typeData['code']) ?>">
                        <?php /* @escapeNotVerified */ echo $this->escapeHtml($typeData['label']) ?>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
      <div class="image-panel" data-role="dialog">
      </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
            <div class="image-panel-preview">
                <img src="<%- data.url %>" alt="<%- data.label %>" />
            </div>
            <div class="image-panel-controls">
                <strong class="image-name"><%- data.label %></strong>

                <fieldset class="admin__fieldset fieldset-image-panel">
                    
                    <div class="admin__field admin__field-inline field-image-size" data-role="size">
                        <label class="admin__field-label">
                            <span><?php /* @escapeNotVerified */ echo __('Image Size') ?></span>
                        </label>
                        <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */ echo __('{size}') ?>"></div>
                    </div>

                    <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                        <label class="admin__field-label">
                            <span><?php /* @escapeNotVerified */ echo __('Image Resolution') ?></span>
                        </label>
                        <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */ echo __('{width}^{height} px') ?>"></div>
                    </div>
                </fieldset>
            </div>
    </script>
    
</div>
<script>
require(['jquery'],function (){
jQuery('body').trigger('contentUpdated');
})
</script>
    